// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: llm/v1/audit_service.proto

package llmv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/aiproxy/pkg/proto/llm/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuditServiceName is the fully-qualified name of the AuditService service.
	AuditServiceName = "llm.v1.AuditService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuditServiceListAuditEventsProcedure is the fully-qualified name of the AuditService's
	// ListAuditEvents RPC.
	AuditServiceListAuditEventsProcedure = "/llm.v1.AuditService/ListAuditEvents"
	// AuditServiceGetRequestTraceProcedure is the fully-qualified name of the AuditService's
	// GetRequestTrace RPC.
	AuditServiceGetRequestTraceProcedure = "/llm.v1.AuditService/GetRequestTrace"
	// AuditServiceCreateExportJobProcedure is the fully-qualified name of the AuditService's
	// CreateExportJob RPC.
	AuditServiceCreateExportJobProcedure = "/llm.v1.AuditService/CreateExportJob"
	// AuditServiceGetExportJobProcedure is the fully-qualified name of the AuditService's GetExportJob
	// RPC.
	AuditServiceGetExportJobProcedure = "/llm.v1.AuditService/GetExportJob"
	// AuditServiceListExportJobsProcedure is the fully-qualified name of the AuditService's
	// ListExportJobs RPC.
	AuditServiceListExportJobsProcedure = "/llm.v1.AuditService/ListExportJobs"
)

// AuditServiceClient is a client for the llm.v1.AuditService service.
type AuditServiceClient interface {
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error)
	GetRequestTrace(context.Context, *connect.Request[v1.GetRequestTraceRequest]) (*connect.Response[v1.GetRequestTraceResponse], error)
	CreateExportJob(context.Context, *connect.Request[v1.CreateExportJobRequest]) (*connect.Response[v1.CreateExportJobResponse], error)
	GetExportJob(context.Context, *connect.Request[v1.GetExportJobRequest]) (*connect.Response[v1.GetExportJobResponse], error)
	ListExportJobs(context.Context, *connect.Request[v1.ListExportJobsRequest]) (*connect.Response[v1.ListExportJobsResponse], error)
}

// NewAuditServiceClient constructs a client for the llm.v1.AuditService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuditServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuditServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	auditServiceMethods := v1.File_llm_v1_audit_service_proto.Services().ByName("AuditService").Methods()
	return &auditServiceClient{
		listAuditEvents: connect.NewClient[v1.ListAuditEventsRequest, v1.ListAuditEventsResponse](
			httpClient,
			baseURL+AuditServiceListAuditEventsProcedure,
			connect.WithSchema(auditServiceMethods.ByName("ListAuditEvents")),
			connect.WithClientOptions(opts...),
		),
		getRequestTrace: connect.NewClient[v1.GetRequestTraceRequest, v1.GetRequestTraceResponse](
			httpClient,
			baseURL+AuditServiceGetRequestTraceProcedure,
			connect.WithSchema(auditServiceMethods.ByName("GetRequestTrace")),
			connect.WithClientOptions(opts...),
		),
		createExportJob: connect.NewClient[v1.CreateExportJobRequest, v1.CreateExportJobResponse](
			httpClient,
			baseURL+AuditServiceCreateExportJobProcedure,
			connect.WithSchema(auditServiceMethods.ByName("CreateExportJob")),
			connect.WithClientOptions(opts...),
		),
		getExportJob: connect.NewClient[v1.GetExportJobRequest, v1.GetExportJobResponse](
			httpClient,
			baseURL+AuditServiceGetExportJobProcedure,
			connect.WithSchema(auditServiceMethods.ByName("GetExportJob")),
			connect.WithClientOptions(opts...),
		),
		listExportJobs: connect.NewClient[v1.ListExportJobsRequest, v1.ListExportJobsResponse](
			httpClient,
			baseURL+AuditServiceListExportJobsProcedure,
			connect.WithSchema(auditServiceMethods.ByName("ListExportJobs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// auditServiceClient implements AuditServiceClient.
type auditServiceClient struct {
	listAuditEvents *connect.Client[v1.ListAuditEventsRequest, v1.ListAuditEventsResponse]
	getRequestTrace *connect.Client[v1.GetRequestTraceRequest, v1.GetRequestTraceResponse]
	createExportJob *connect.Client[v1.CreateExportJobRequest, v1.CreateExportJobResponse]
	getExportJob    *connect.Client[v1.GetExportJobRequest, v1.GetExportJobResponse]
	listExportJobs  *connect.Client[v1.ListExportJobsRequest, v1.ListExportJobsResponse]
}

// ListAuditEvents calls llm.v1.AuditService.ListAuditEvents.
func (c *auditServiceClient) ListAuditEvents(ctx context.Context, req *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error) {
	return c.listAuditEvents.CallUnary(ctx, req)
}

// GetRequestTrace calls llm.v1.AuditService.GetRequestTrace.
func (c *auditServiceClient) GetRequestTrace(ctx context.Context, req *connect.Request[v1.GetRequestTraceRequest]) (*connect.Response[v1.GetRequestTraceResponse], error) {
	return c.getRequestTrace.CallUnary(ctx, req)
}

// CreateExportJob calls llm.v1.AuditService.CreateExportJob.
func (c *auditServiceClient) CreateExportJob(ctx context.Context, req *connect.Request[v1.CreateExportJobRequest]) (*connect.Response[v1.CreateExportJobResponse], error) {
	return c.createExportJob.CallUnary(ctx, req)
}

// GetExportJob calls llm.v1.AuditService.GetExportJob.
func (c *auditServiceClient) GetExportJob(ctx context.Context, req *connect.Request[v1.GetExportJobRequest]) (*connect.Response[v1.GetExportJobResponse], error) {
	return c.getExportJob.CallUnary(ctx, req)
}

// ListExportJobs calls llm.v1.AuditService.ListExportJobs.
func (c *auditServiceClient) ListExportJobs(ctx context.Context, req *connect.Request[v1.ListExportJobsRequest]) (*connect.Response[v1.ListExportJobsResponse], error) {
	return c.listExportJobs.CallUnary(ctx, req)
}

// AuditServiceHandler is an implementation of the llm.v1.AuditService service.
type AuditServiceHandler interface {
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error)
	GetRequestTrace(context.Context, *connect.Request[v1.GetRequestTraceRequest]) (*connect.Response[v1.GetRequestTraceResponse], error)
	CreateExportJob(context.Context, *connect.Request[v1.CreateExportJobRequest]) (*connect.Response[v1.CreateExportJobResponse], error)
	GetExportJob(context.Context, *connect.Request[v1.GetExportJobRequest]) (*connect.Response[v1.GetExportJobResponse], error)
	ListExportJobs(context.Context, *connect.Request[v1.ListExportJobsRequest]) (*connect.Response[v1.ListExportJobsResponse], error)
}

// NewAuditServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuditServiceHandler(svc AuditServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	auditServiceMethods := v1.File_llm_v1_audit_service_proto.Services().ByName("AuditService").Methods()
	auditServiceListAuditEventsHandler := connect.NewUnaryHandler(
		AuditServiceListAuditEventsProcedure,
		svc.ListAuditEvents,
		connect.WithSchema(auditServiceMethods.ByName("ListAuditEvents")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceGetRequestTraceHandler := connect.NewUnaryHandler(
		AuditServiceGetRequestTraceProcedure,
		svc.GetRequestTrace,
		connect.WithSchema(auditServiceMethods.ByName("GetRequestTrace")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceCreateExportJobHandler := connect.NewUnaryHandler(
		AuditServiceCreateExportJobProcedure,
		svc.CreateExportJob,
		connect.WithSchema(auditServiceMethods.ByName("CreateExportJob")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceGetExportJobHandler := connect.NewUnaryHandler(
		AuditServiceGetExportJobProcedure,
		svc.GetExportJob,
		connect.WithSchema(auditServiceMethods.ByName("GetExportJob")),
		connect.WithHandlerOptions(opts...),
	)
	auditServiceListExportJobsHandler := connect.NewUnaryHandler(
		AuditServiceListExportJobsProcedure,
		svc.ListExportJobs,
		connect.WithSchema(auditServiceMethods.ByName("ListExportJobs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.AuditService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuditServiceListAuditEventsProcedure:
			auditServiceListAuditEventsHandler.ServeHTTP(w, r)
		case AuditServiceGetRequestTraceProcedure:
			auditServiceGetRequestTraceHandler.ServeHTTP(w, r)
		case AuditServiceCreateExportJobProcedure:
			auditServiceCreateExportJobHandler.ServeHTTP(w, r)
		case AuditServiceGetExportJobProcedure:
			auditServiceGetExportJobHandler.ServeHTTP(w, r)
		case AuditServiceListExportJobsProcedure:
			auditServiceListExportJobsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuditServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuditServiceHandler struct{}

func (UnimplementedAuditServiceHandler) ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.ListAuditEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.AuditService.ListAuditEvents is not implemented"))
}

func (UnimplementedAuditServiceHandler) GetRequestTrace(context.Context, *connect.Request[v1.GetRequestTraceRequest]) (*connect.Response[v1.GetRequestTraceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.AuditService.GetRequestTrace is not implemented"))
}

func (UnimplementedAuditServiceHandler) CreateExportJob(context.Context, *connect.Request[v1.CreateExportJobRequest]) (*connect.Response[v1.CreateExportJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.AuditService.CreateExportJob is not implemented"))
}

func (UnimplementedAuditServiceHandler) GetExportJob(context.Context, *connect.Request[v1.GetExportJobRequest]) (*connect.Response[v1.GetExportJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.AuditService.GetExportJob is not implemented"))
}

func (UnimplementedAuditServiceHandler) ListExportJobs(context.Context, *connect.Request[v1.ListExportJobsRequest]) (*connect.Response[v1.ListExportJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.AuditService.ListExportJobs is not implemented"))
}
