// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: llm/v1/tenant_service.proto

package llmv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/aiproxy/pkg/proto/llm/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TenantServiceName is the fully-qualified name of the TenantService service.
	TenantServiceName = "llm.v1.TenantService"
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "llm.v1.ProjectService"
	// MembershipServiceName is the fully-qualified name of the MembershipService service.
	MembershipServiceName = "llm.v1.MembershipService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TenantServiceCreateTenantProcedure is the fully-qualified name of the TenantService's
	// CreateTenant RPC.
	TenantServiceCreateTenantProcedure = "/llm.v1.TenantService/CreateTenant"
	// TenantServiceGetTenantProcedure is the fully-qualified name of the TenantService's GetTenant RPC.
	TenantServiceGetTenantProcedure = "/llm.v1.TenantService/GetTenant"
	// TenantServiceListTenantsProcedure is the fully-qualified name of the TenantService's ListTenants
	// RPC.
	TenantServiceListTenantsProcedure = "/llm.v1.TenantService/ListTenants"
	// TenantServiceUpdateTenantProcedure is the fully-qualified name of the TenantService's
	// UpdateTenant RPC.
	TenantServiceUpdateTenantProcedure = "/llm.v1.TenantService/UpdateTenant"
	// TenantServiceSuspendTenantProcedure is the fully-qualified name of the TenantService's
	// SuspendTenant RPC.
	TenantServiceSuspendTenantProcedure = "/llm.v1.TenantService/SuspendTenant"
	// TenantServiceArchiveTenantProcedure is the fully-qualified name of the TenantService's
	// ArchiveTenant RPC.
	TenantServiceArchiveTenantProcedure = "/llm.v1.TenantService/ArchiveTenant"
	// ProjectServiceCreateProjectProcedure is the fully-qualified name of the ProjectService's
	// CreateProject RPC.
	ProjectServiceCreateProjectProcedure = "/llm.v1.ProjectService/CreateProject"
	// ProjectServiceGetProjectProcedure is the fully-qualified name of the ProjectService's GetProject
	// RPC.
	ProjectServiceGetProjectProcedure = "/llm.v1.ProjectService/GetProject"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/llm.v1.ProjectService/ListProjects"
	// ProjectServiceUpdateProjectProcedure is the fully-qualified name of the ProjectService's
	// UpdateProject RPC.
	ProjectServiceUpdateProjectProcedure = "/llm.v1.ProjectService/UpdateProject"
	// ProjectServiceArchiveProjectProcedure is the fully-qualified name of the ProjectService's
	// ArchiveProject RPC.
	ProjectServiceArchiveProjectProcedure = "/llm.v1.ProjectService/ArchiveProject"
	// MembershipServiceCreateMembershipProcedure is the fully-qualified name of the MembershipService's
	// CreateMembership RPC.
	MembershipServiceCreateMembershipProcedure = "/llm.v1.MembershipService/CreateMembership"
	// MembershipServiceListMembershipsProcedure is the fully-qualified name of the MembershipService's
	// ListMemberships RPC.
	MembershipServiceListMembershipsProcedure = "/llm.v1.MembershipService/ListMemberships"
	// MembershipServiceDeleteMembershipProcedure is the fully-qualified name of the MembershipService's
	// DeleteMembership RPC.
	MembershipServiceDeleteMembershipProcedure = "/llm.v1.MembershipService/DeleteMembership"
)

// TenantServiceClient is a client for the llm.v1.TenantService service.
type TenantServiceClient interface {
	CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.CreateTenantResponse], error)
	GetTenant(context.Context, *connect.Request[v1.GetTenantRequest]) (*connect.Response[v1.GetTenantResponse], error)
	ListTenants(context.Context, *connect.Request[v1.ListTenantsRequest]) (*connect.Response[v1.ListTenantsResponse], error)
	UpdateTenant(context.Context, *connect.Request[v1.UpdateTenantRequest]) (*connect.Response[v1.UpdateTenantResponse], error)
	SuspendTenant(context.Context, *connect.Request[v1.SuspendTenantRequest]) (*connect.Response[v1.SuspendTenantResponse], error)
	ArchiveTenant(context.Context, *connect.Request[v1.ArchiveTenantRequest]) (*connect.Response[v1.ArchiveTenantResponse], error)
}

// NewTenantServiceClient constructs a client for the llm.v1.TenantService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTenantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TenantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tenantServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("TenantService").Methods()
	return &tenantServiceClient{
		createTenant: connect.NewClient[v1.CreateTenantRequest, v1.CreateTenantResponse](
			httpClient,
			baseURL+TenantServiceCreateTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("CreateTenant")),
			connect.WithClientOptions(opts...),
		),
		getTenant: connect.NewClient[v1.GetTenantRequest, v1.GetTenantResponse](
			httpClient,
			baseURL+TenantServiceGetTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("GetTenant")),
			connect.WithClientOptions(opts...),
		),
		listTenants: connect.NewClient[v1.ListTenantsRequest, v1.ListTenantsResponse](
			httpClient,
			baseURL+TenantServiceListTenantsProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ListTenants")),
			connect.WithClientOptions(opts...),
		),
		updateTenant: connect.NewClient[v1.UpdateTenantRequest, v1.UpdateTenantResponse](
			httpClient,
			baseURL+TenantServiceUpdateTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("UpdateTenant")),
			connect.WithClientOptions(opts...),
		),
		suspendTenant: connect.NewClient[v1.SuspendTenantRequest, v1.SuspendTenantResponse](
			httpClient,
			baseURL+TenantServiceSuspendTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("SuspendTenant")),
			connect.WithClientOptions(opts...),
		),
		archiveTenant: connect.NewClient[v1.ArchiveTenantRequest, v1.ArchiveTenantResponse](
			httpClient,
			baseURL+TenantServiceArchiveTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ArchiveTenant")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tenantServiceClient implements TenantServiceClient.
type tenantServiceClient struct {
	createTenant  *connect.Client[v1.CreateTenantRequest, v1.CreateTenantResponse]
	getTenant     *connect.Client[v1.GetTenantRequest, v1.GetTenantResponse]
	listTenants   *connect.Client[v1.ListTenantsRequest, v1.ListTenantsResponse]
	updateTenant  *connect.Client[v1.UpdateTenantRequest, v1.UpdateTenantResponse]
	suspendTenant *connect.Client[v1.SuspendTenantRequest, v1.SuspendTenantResponse]
	archiveTenant *connect.Client[v1.ArchiveTenantRequest, v1.ArchiveTenantResponse]
}

// CreateTenant calls llm.v1.TenantService.CreateTenant.
func (c *tenantServiceClient) CreateTenant(ctx context.Context, req *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.CreateTenantResponse], error) {
	return c.createTenant.CallUnary(ctx, req)
}

// GetTenant calls llm.v1.TenantService.GetTenant.
func (c *tenantServiceClient) GetTenant(ctx context.Context, req *connect.Request[v1.GetTenantRequest]) (*connect.Response[v1.GetTenantResponse], error) {
	return c.getTenant.CallUnary(ctx, req)
}

// ListTenants calls llm.v1.TenantService.ListTenants.
func (c *tenantServiceClient) ListTenants(ctx context.Context, req *connect.Request[v1.ListTenantsRequest]) (*connect.Response[v1.ListTenantsResponse], error) {
	return c.listTenants.CallUnary(ctx, req)
}

// UpdateTenant calls llm.v1.TenantService.UpdateTenant.
func (c *tenantServiceClient) UpdateTenant(ctx context.Context, req *connect.Request[v1.UpdateTenantRequest]) (*connect.Response[v1.UpdateTenantResponse], error) {
	return c.updateTenant.CallUnary(ctx, req)
}

// SuspendTenant calls llm.v1.TenantService.SuspendTenant.
func (c *tenantServiceClient) SuspendTenant(ctx context.Context, req *connect.Request[v1.SuspendTenantRequest]) (*connect.Response[v1.SuspendTenantResponse], error) {
	return c.suspendTenant.CallUnary(ctx, req)
}

// ArchiveTenant calls llm.v1.TenantService.ArchiveTenant.
func (c *tenantServiceClient) ArchiveTenant(ctx context.Context, req *connect.Request[v1.ArchiveTenantRequest]) (*connect.Response[v1.ArchiveTenantResponse], error) {
	return c.archiveTenant.CallUnary(ctx, req)
}

// TenantServiceHandler is an implementation of the llm.v1.TenantService service.
type TenantServiceHandler interface {
	CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.CreateTenantResponse], error)
	GetTenant(context.Context, *connect.Request[v1.GetTenantRequest]) (*connect.Response[v1.GetTenantResponse], error)
	ListTenants(context.Context, *connect.Request[v1.ListTenantsRequest]) (*connect.Response[v1.ListTenantsResponse], error)
	UpdateTenant(context.Context, *connect.Request[v1.UpdateTenantRequest]) (*connect.Response[v1.UpdateTenantResponse], error)
	SuspendTenant(context.Context, *connect.Request[v1.SuspendTenantRequest]) (*connect.Response[v1.SuspendTenantResponse], error)
	ArchiveTenant(context.Context, *connect.Request[v1.ArchiveTenantRequest]) (*connect.Response[v1.ArchiveTenantResponse], error)
}

// NewTenantServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTenantServiceHandler(svc TenantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tenantServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("TenantService").Methods()
	tenantServiceCreateTenantHandler := connect.NewUnaryHandler(
		TenantServiceCreateTenantProcedure,
		svc.CreateTenant,
		connect.WithSchema(tenantServiceMethods.ByName("CreateTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceGetTenantHandler := connect.NewUnaryHandler(
		TenantServiceGetTenantProcedure,
		svc.GetTenant,
		connect.WithSchema(tenantServiceMethods.ByName("GetTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceListTenantsHandler := connect.NewUnaryHandler(
		TenantServiceListTenantsProcedure,
		svc.ListTenants,
		connect.WithSchema(tenantServiceMethods.ByName("ListTenants")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateTenantHandler := connect.NewUnaryHandler(
		TenantServiceUpdateTenantProcedure,
		svc.UpdateTenant,
		connect.WithSchema(tenantServiceMethods.ByName("UpdateTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceSuspendTenantHandler := connect.NewUnaryHandler(
		TenantServiceSuspendTenantProcedure,
		svc.SuspendTenant,
		connect.WithSchema(tenantServiceMethods.ByName("SuspendTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceArchiveTenantHandler := connect.NewUnaryHandler(
		TenantServiceArchiveTenantProcedure,
		svc.ArchiveTenant,
		connect.WithSchema(tenantServiceMethods.ByName("ArchiveTenant")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.TenantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TenantServiceCreateTenantProcedure:
			tenantServiceCreateTenantHandler.ServeHTTP(w, r)
		case TenantServiceGetTenantProcedure:
			tenantServiceGetTenantHandler.ServeHTTP(w, r)
		case TenantServiceListTenantsProcedure:
			tenantServiceListTenantsHandler.ServeHTTP(w, r)
		case TenantServiceUpdateTenantProcedure:
			tenantServiceUpdateTenantHandler.ServeHTTP(w, r)
		case TenantServiceSuspendTenantProcedure:
			tenantServiceSuspendTenantHandler.ServeHTTP(w, r)
		case TenantServiceArchiveTenantProcedure:
			tenantServiceArchiveTenantHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTenantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantServiceHandler struct{}

func (UnimplementedTenantServiceHandler) CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.CreateTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.CreateTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) GetTenant(context.Context, *connect.Request[v1.GetTenantRequest]) (*connect.Response[v1.GetTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.GetTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) ListTenants(context.Context, *connect.Request[v1.ListTenantsRequest]) (*connect.Response[v1.ListTenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.ListTenants is not implemented"))
}

func (UnimplementedTenantServiceHandler) UpdateTenant(context.Context, *connect.Request[v1.UpdateTenantRequest]) (*connect.Response[v1.UpdateTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.UpdateTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) SuspendTenant(context.Context, *connect.Request[v1.SuspendTenantRequest]) (*connect.Response[v1.SuspendTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.SuspendTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) ArchiveTenant(context.Context, *connect.Request[v1.ArchiveTenantRequest]) (*connect.Response[v1.ArchiveTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.TenantService.ArchiveTenant is not implemented"))
}

// ProjectServiceClient is a client for the llm.v1.ProjectService service.
type ProjectServiceClient interface {
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error)
}

// NewProjectServiceClient constructs a client for the llm.v1.ProjectService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+ProjectServiceCreateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v1.GetProjectRequest, v1.GetProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.UpdateProjectResponse](
			httpClient,
			baseURL+ProjectServiceUpdateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		archiveProject: connect.NewClient[v1.ArchiveProjectRequest, v1.ArchiveProjectResponse](
			httpClient,
			baseURL+ProjectServiceArchiveProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ArchiveProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	createProject  *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	getProject     *connect.Client[v1.GetProjectRequest, v1.GetProjectResponse]
	listProjects   *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	updateProject  *connect.Client[v1.UpdateProjectRequest, v1.UpdateProjectResponse]
	archiveProject *connect.Client[v1.ArchiveProjectRequest, v1.ArchiveProjectResponse]
}

// CreateProject calls llm.v1.ProjectService.CreateProject.
func (c *projectServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// GetProject calls llm.v1.ProjectService.GetProject.
func (c *projectServiceClient) GetProject(ctx context.Context, req *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// ListProjects calls llm.v1.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// UpdateProject calls llm.v1.ProjectService.UpdateProject.
func (c *projectServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// ArchiveProject calls llm.v1.ProjectService.ArchiveProject.
func (c *projectServiceClient) ArchiveProject(ctx context.Context, req *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error) {
	return c.archiveProject.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the llm.v1.ProjectService service.
type ProjectServiceHandler interface {
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("ProjectService").Methods()
	projectServiceCreateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetProjectHandler := connect.NewUnaryHandler(
		ProjectServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(projectServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(projectServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceArchiveProjectHandler := connect.NewUnaryHandler(
		ProjectServiceArchiveProjectProcedure,
		svc.ArchiveProject,
		connect.WithSchema(projectServiceMethods.ByName("ArchiveProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceCreateProjectProcedure:
			projectServiceCreateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceGetProjectProcedure:
			projectServiceGetProjectHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceUpdateProjectProcedure:
			projectServiceUpdateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceArchiveProjectProcedure:
			projectServiceArchiveProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ProjectService.CreateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ProjectService.GetProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ProjectService.UpdateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ArchiveProject(context.Context, *connect.Request[v1.ArchiveProjectRequest]) (*connect.Response[v1.ArchiveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ProjectService.ArchiveProject is not implemented"))
}

// MembershipServiceClient is a client for the llm.v1.MembershipService service.
type MembershipServiceClient interface {
	CreateMembership(context.Context, *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error)
	ListMemberships(context.Context, *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error)
	DeleteMembership(context.Context, *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error)
}

// NewMembershipServiceClient constructs a client for the llm.v1.MembershipService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMembershipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MembershipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	membershipServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("MembershipService").Methods()
	return &membershipServiceClient{
		createMembership: connect.NewClient[v1.CreateMembershipRequest, v1.CreateMembershipResponse](
			httpClient,
			baseURL+MembershipServiceCreateMembershipProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("CreateMembership")),
			connect.WithClientOptions(opts...),
		),
		listMemberships: connect.NewClient[v1.ListMembershipsRequest, v1.ListMembershipsResponse](
			httpClient,
			baseURL+MembershipServiceListMembershipsProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("ListMemberships")),
			connect.WithClientOptions(opts...),
		),
		deleteMembership: connect.NewClient[v1.DeleteMembershipRequest, v1.DeleteMembershipResponse](
			httpClient,
			baseURL+MembershipServiceDeleteMembershipProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("DeleteMembership")),
			connect.WithClientOptions(opts...),
		),
	}
}

// membershipServiceClient implements MembershipServiceClient.
type membershipServiceClient struct {
	createMembership *connect.Client[v1.CreateMembershipRequest, v1.CreateMembershipResponse]
	listMemberships  *connect.Client[v1.ListMembershipsRequest, v1.ListMembershipsResponse]
	deleteMembership *connect.Client[v1.DeleteMembershipRequest, v1.DeleteMembershipResponse]
}

// CreateMembership calls llm.v1.MembershipService.CreateMembership.
func (c *membershipServiceClient) CreateMembership(ctx context.Context, req *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error) {
	return c.createMembership.CallUnary(ctx, req)
}

// ListMemberships calls llm.v1.MembershipService.ListMemberships.
func (c *membershipServiceClient) ListMemberships(ctx context.Context, req *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error) {
	return c.listMemberships.CallUnary(ctx, req)
}

// DeleteMembership calls llm.v1.MembershipService.DeleteMembership.
func (c *membershipServiceClient) DeleteMembership(ctx context.Context, req *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error) {
	return c.deleteMembership.CallUnary(ctx, req)
}

// MembershipServiceHandler is an implementation of the llm.v1.MembershipService service.
type MembershipServiceHandler interface {
	CreateMembership(context.Context, *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error)
	ListMemberships(context.Context, *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error)
	DeleteMembership(context.Context, *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error)
}

// NewMembershipServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMembershipServiceHandler(svc MembershipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	membershipServiceMethods := v1.File_llm_v1_tenant_service_proto.Services().ByName("MembershipService").Methods()
	membershipServiceCreateMembershipHandler := connect.NewUnaryHandler(
		MembershipServiceCreateMembershipProcedure,
		svc.CreateMembership,
		connect.WithSchema(membershipServiceMethods.ByName("CreateMembership")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceListMembershipsHandler := connect.NewUnaryHandler(
		MembershipServiceListMembershipsProcedure,
		svc.ListMemberships,
		connect.WithSchema(membershipServiceMethods.ByName("ListMemberships")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceDeleteMembershipHandler := connect.NewUnaryHandler(
		MembershipServiceDeleteMembershipProcedure,
		svc.DeleteMembership,
		connect.WithSchema(membershipServiceMethods.ByName("DeleteMembership")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.MembershipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MembershipServiceCreateMembershipProcedure:
			membershipServiceCreateMembershipHandler.ServeHTTP(w, r)
		case MembershipServiceListMembershipsProcedure:
			membershipServiceListMembershipsHandler.ServeHTTP(w, r)
		case MembershipServiceDeleteMembershipProcedure:
			membershipServiceDeleteMembershipHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMembershipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMembershipServiceHandler struct{}

func (UnimplementedMembershipServiceHandler) CreateMembership(context.Context, *connect.Request[v1.CreateMembershipRequest]) (*connect.Response[v1.CreateMembershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.MembershipService.CreateMembership is not implemented"))
}

func (UnimplementedMembershipServiceHandler) ListMemberships(context.Context, *connect.Request[v1.ListMembershipsRequest]) (*connect.Response[v1.ListMembershipsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.MembershipService.ListMemberships is not implemented"))
}

func (UnimplementedMembershipServiceHandler) DeleteMembership(context.Context, *connect.Request[v1.DeleteMembershipRequest]) (*connect.Response[v1.DeleteMembershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.MembershipService.DeleteMembership is not implemented"))
}
