// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: llm/v1/vendor_service.proto

package llmv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/aiproxy/pkg/proto/llm/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VendorServiceName is the fully-qualified name of the VendorService service.
	VendorServiceName = "llm.v1.VendorService"
	// ModelCatalogServiceName is the fully-qualified name of the ModelCatalogService service.
	ModelCatalogServiceName = "llm.v1.ModelCatalogService"
	// RoutingPolicyServiceName is the fully-qualified name of the RoutingPolicyService service.
	RoutingPolicyServiceName = "llm.v1.RoutingPolicyService"
	// QuotaPolicyServiceName is the fully-qualified name of the QuotaPolicyService service.
	QuotaPolicyServiceName = "llm.v1.QuotaPolicyService"
	// SpendPolicyServiceName is the fully-qualified name of the SpendPolicyService service.
	SpendPolicyServiceName = "llm.v1.SpendPolicyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VendorServiceCreateVendorProcedure is the fully-qualified name of the VendorService's
	// CreateVendor RPC.
	VendorServiceCreateVendorProcedure = "/llm.v1.VendorService/CreateVendor"
	// VendorServiceGetVendorProcedure is the fully-qualified name of the VendorService's GetVendor RPC.
	VendorServiceGetVendorProcedure = "/llm.v1.VendorService/GetVendor"
	// VendorServiceListVendorsProcedure is the fully-qualified name of the VendorService's ListVendors
	// RPC.
	VendorServiceListVendorsProcedure = "/llm.v1.VendorService/ListVendors"
	// VendorServiceUpdateVendorProcedure is the fully-qualified name of the VendorService's
	// UpdateVendor RPC.
	VendorServiceUpdateVendorProcedure = "/llm.v1.VendorService/UpdateVendor"
	// ModelCatalogServiceCreateLogicalModelProcedure is the fully-qualified name of the
	// ModelCatalogService's CreateLogicalModel RPC.
	ModelCatalogServiceCreateLogicalModelProcedure = "/llm.v1.ModelCatalogService/CreateLogicalModel"
	// ModelCatalogServiceGetLogicalModelProcedure is the fully-qualified name of the
	// ModelCatalogService's GetLogicalModel RPC.
	ModelCatalogServiceGetLogicalModelProcedure = "/llm.v1.ModelCatalogService/GetLogicalModel"
	// ModelCatalogServiceListLogicalModelsProcedure is the fully-qualified name of the
	// ModelCatalogService's ListLogicalModels RPC.
	ModelCatalogServiceListLogicalModelsProcedure = "/llm.v1.ModelCatalogService/ListLogicalModels"
	// ModelCatalogServiceUpdateLogicalModelProcedure is the fully-qualified name of the
	// ModelCatalogService's UpdateLogicalModel RPC.
	ModelCatalogServiceUpdateLogicalModelProcedure = "/llm.v1.ModelCatalogService/UpdateLogicalModel"
	// RoutingPolicyServiceCreateRoutingPolicyProcedure is the fully-qualified name of the
	// RoutingPolicyService's CreateRoutingPolicy RPC.
	RoutingPolicyServiceCreateRoutingPolicyProcedure = "/llm.v1.RoutingPolicyService/CreateRoutingPolicy"
	// RoutingPolicyServiceGetRoutingPolicyProcedure is the fully-qualified name of the
	// RoutingPolicyService's GetRoutingPolicy RPC.
	RoutingPolicyServiceGetRoutingPolicyProcedure = "/llm.v1.RoutingPolicyService/GetRoutingPolicy"
	// RoutingPolicyServiceListRoutingPoliciesProcedure is the fully-qualified name of the
	// RoutingPolicyService's ListRoutingPolicies RPC.
	RoutingPolicyServiceListRoutingPoliciesProcedure = "/llm.v1.RoutingPolicyService/ListRoutingPolicies"
	// RoutingPolicyServiceUpdateRoutingPolicyProcedure is the fully-qualified name of the
	// RoutingPolicyService's UpdateRoutingPolicy RPC.
	RoutingPolicyServiceUpdateRoutingPolicyProcedure = "/llm.v1.RoutingPolicyService/UpdateRoutingPolicy"
	// QuotaPolicyServiceCreateQuotaPolicyProcedure is the fully-qualified name of the
	// QuotaPolicyService's CreateQuotaPolicy RPC.
	QuotaPolicyServiceCreateQuotaPolicyProcedure = "/llm.v1.QuotaPolicyService/CreateQuotaPolicy"
	// QuotaPolicyServiceGetQuotaPolicyProcedure is the fully-qualified name of the QuotaPolicyService's
	// GetQuotaPolicy RPC.
	QuotaPolicyServiceGetQuotaPolicyProcedure = "/llm.v1.QuotaPolicyService/GetQuotaPolicy"
	// QuotaPolicyServiceListQuotaPoliciesProcedure is the fully-qualified name of the
	// QuotaPolicyService's ListQuotaPolicies RPC.
	QuotaPolicyServiceListQuotaPoliciesProcedure = "/llm.v1.QuotaPolicyService/ListQuotaPolicies"
	// QuotaPolicyServiceUpdateQuotaPolicyProcedure is the fully-qualified name of the
	// QuotaPolicyService's UpdateQuotaPolicy RPC.
	QuotaPolicyServiceUpdateQuotaPolicyProcedure = "/llm.v1.QuotaPolicyService/UpdateQuotaPolicy"
	// SpendPolicyServiceCreateSpendPolicyProcedure is the fully-qualified name of the
	// SpendPolicyService's CreateSpendPolicy RPC.
	SpendPolicyServiceCreateSpendPolicyProcedure = "/llm.v1.SpendPolicyService/CreateSpendPolicy"
	// SpendPolicyServiceGetSpendPolicyProcedure is the fully-qualified name of the SpendPolicyService's
	// GetSpendPolicy RPC.
	SpendPolicyServiceGetSpendPolicyProcedure = "/llm.v1.SpendPolicyService/GetSpendPolicy"
	// SpendPolicyServiceListSpendPoliciesProcedure is the fully-qualified name of the
	// SpendPolicyService's ListSpendPolicies RPC.
	SpendPolicyServiceListSpendPoliciesProcedure = "/llm.v1.SpendPolicyService/ListSpendPolicies"
	// SpendPolicyServiceUpdateSpendPolicyProcedure is the fully-qualified name of the
	// SpendPolicyService's UpdateSpendPolicy RPC.
	SpendPolicyServiceUpdateSpendPolicyProcedure = "/llm.v1.SpendPolicyService/UpdateSpendPolicy"
)

// VendorServiceClient is a client for the llm.v1.VendorService service.
type VendorServiceClient interface {
	CreateVendor(context.Context, *connect.Request[v1.CreateVendorRequest]) (*connect.Response[v1.CreateVendorResponse], error)
	GetVendor(context.Context, *connect.Request[v1.GetVendorRequest]) (*connect.Response[v1.GetVendorResponse], error)
	ListVendors(context.Context, *connect.Request[v1.ListVendorsRequest]) (*connect.Response[v1.ListVendorsResponse], error)
	UpdateVendor(context.Context, *connect.Request[v1.UpdateVendorRequest]) (*connect.Response[v1.UpdateVendorResponse], error)
}

// NewVendorServiceClient constructs a client for the llm.v1.VendorService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVendorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VendorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	vendorServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("VendorService").Methods()
	return &vendorServiceClient{
		createVendor: connect.NewClient[v1.CreateVendorRequest, v1.CreateVendorResponse](
			httpClient,
			baseURL+VendorServiceCreateVendorProcedure,
			connect.WithSchema(vendorServiceMethods.ByName("CreateVendor")),
			connect.WithClientOptions(opts...),
		),
		getVendor: connect.NewClient[v1.GetVendorRequest, v1.GetVendorResponse](
			httpClient,
			baseURL+VendorServiceGetVendorProcedure,
			connect.WithSchema(vendorServiceMethods.ByName("GetVendor")),
			connect.WithClientOptions(opts...),
		),
		listVendors: connect.NewClient[v1.ListVendorsRequest, v1.ListVendorsResponse](
			httpClient,
			baseURL+VendorServiceListVendorsProcedure,
			connect.WithSchema(vendorServiceMethods.ByName("ListVendors")),
			connect.WithClientOptions(opts...),
		),
		updateVendor: connect.NewClient[v1.UpdateVendorRequest, v1.UpdateVendorResponse](
			httpClient,
			baseURL+VendorServiceUpdateVendorProcedure,
			connect.WithSchema(vendorServiceMethods.ByName("UpdateVendor")),
			connect.WithClientOptions(opts...),
		),
	}
}

// vendorServiceClient implements VendorServiceClient.
type vendorServiceClient struct {
	createVendor *connect.Client[v1.CreateVendorRequest, v1.CreateVendorResponse]
	getVendor    *connect.Client[v1.GetVendorRequest, v1.GetVendorResponse]
	listVendors  *connect.Client[v1.ListVendorsRequest, v1.ListVendorsResponse]
	updateVendor *connect.Client[v1.UpdateVendorRequest, v1.UpdateVendorResponse]
}

// CreateVendor calls llm.v1.VendorService.CreateVendor.
func (c *vendorServiceClient) CreateVendor(ctx context.Context, req *connect.Request[v1.CreateVendorRequest]) (*connect.Response[v1.CreateVendorResponse], error) {
	return c.createVendor.CallUnary(ctx, req)
}

// GetVendor calls llm.v1.VendorService.GetVendor.
func (c *vendorServiceClient) GetVendor(ctx context.Context, req *connect.Request[v1.GetVendorRequest]) (*connect.Response[v1.GetVendorResponse], error) {
	return c.getVendor.CallUnary(ctx, req)
}

// ListVendors calls llm.v1.VendorService.ListVendors.
func (c *vendorServiceClient) ListVendors(ctx context.Context, req *connect.Request[v1.ListVendorsRequest]) (*connect.Response[v1.ListVendorsResponse], error) {
	return c.listVendors.CallUnary(ctx, req)
}

// UpdateVendor calls llm.v1.VendorService.UpdateVendor.
func (c *vendorServiceClient) UpdateVendor(ctx context.Context, req *connect.Request[v1.UpdateVendorRequest]) (*connect.Response[v1.UpdateVendorResponse], error) {
	return c.updateVendor.CallUnary(ctx, req)
}

// VendorServiceHandler is an implementation of the llm.v1.VendorService service.
type VendorServiceHandler interface {
	CreateVendor(context.Context, *connect.Request[v1.CreateVendorRequest]) (*connect.Response[v1.CreateVendorResponse], error)
	GetVendor(context.Context, *connect.Request[v1.GetVendorRequest]) (*connect.Response[v1.GetVendorResponse], error)
	ListVendors(context.Context, *connect.Request[v1.ListVendorsRequest]) (*connect.Response[v1.ListVendorsResponse], error)
	UpdateVendor(context.Context, *connect.Request[v1.UpdateVendorRequest]) (*connect.Response[v1.UpdateVendorResponse], error)
}

// NewVendorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVendorServiceHandler(svc VendorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	vendorServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("VendorService").Methods()
	vendorServiceCreateVendorHandler := connect.NewUnaryHandler(
		VendorServiceCreateVendorProcedure,
		svc.CreateVendor,
		connect.WithSchema(vendorServiceMethods.ByName("CreateVendor")),
		connect.WithHandlerOptions(opts...),
	)
	vendorServiceGetVendorHandler := connect.NewUnaryHandler(
		VendorServiceGetVendorProcedure,
		svc.GetVendor,
		connect.WithSchema(vendorServiceMethods.ByName("GetVendor")),
		connect.WithHandlerOptions(opts...),
	)
	vendorServiceListVendorsHandler := connect.NewUnaryHandler(
		VendorServiceListVendorsProcedure,
		svc.ListVendors,
		connect.WithSchema(vendorServiceMethods.ByName("ListVendors")),
		connect.WithHandlerOptions(opts...),
	)
	vendorServiceUpdateVendorHandler := connect.NewUnaryHandler(
		VendorServiceUpdateVendorProcedure,
		svc.UpdateVendor,
		connect.WithSchema(vendorServiceMethods.ByName("UpdateVendor")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.VendorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VendorServiceCreateVendorProcedure:
			vendorServiceCreateVendorHandler.ServeHTTP(w, r)
		case VendorServiceGetVendorProcedure:
			vendorServiceGetVendorHandler.ServeHTTP(w, r)
		case VendorServiceListVendorsProcedure:
			vendorServiceListVendorsHandler.ServeHTTP(w, r)
		case VendorServiceUpdateVendorProcedure:
			vendorServiceUpdateVendorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVendorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVendorServiceHandler struct{}

func (UnimplementedVendorServiceHandler) CreateVendor(context.Context, *connect.Request[v1.CreateVendorRequest]) (*connect.Response[v1.CreateVendorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.VendorService.CreateVendor is not implemented"))
}

func (UnimplementedVendorServiceHandler) GetVendor(context.Context, *connect.Request[v1.GetVendorRequest]) (*connect.Response[v1.GetVendorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.VendorService.GetVendor is not implemented"))
}

func (UnimplementedVendorServiceHandler) ListVendors(context.Context, *connect.Request[v1.ListVendorsRequest]) (*connect.Response[v1.ListVendorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.VendorService.ListVendors is not implemented"))
}

func (UnimplementedVendorServiceHandler) UpdateVendor(context.Context, *connect.Request[v1.UpdateVendorRequest]) (*connect.Response[v1.UpdateVendorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.VendorService.UpdateVendor is not implemented"))
}

// ModelCatalogServiceClient is a client for the llm.v1.ModelCatalogService service.
type ModelCatalogServiceClient interface {
	CreateLogicalModel(context.Context, *connect.Request[v1.CreateLogicalModelRequest]) (*connect.Response[v1.CreateLogicalModelResponse], error)
	GetLogicalModel(context.Context, *connect.Request[v1.GetLogicalModelRequest]) (*connect.Response[v1.GetLogicalModelResponse], error)
	ListLogicalModels(context.Context, *connect.Request[v1.ListLogicalModelsRequest]) (*connect.Response[v1.ListLogicalModelsResponse], error)
	UpdateLogicalModel(context.Context, *connect.Request[v1.UpdateLogicalModelRequest]) (*connect.Response[v1.UpdateLogicalModelResponse], error)
}

// NewModelCatalogServiceClient constructs a client for the llm.v1.ModelCatalogService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelCatalogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelCatalogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelCatalogServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("ModelCatalogService").Methods()
	return &modelCatalogServiceClient{
		createLogicalModel: connect.NewClient[v1.CreateLogicalModelRequest, v1.CreateLogicalModelResponse](
			httpClient,
			baseURL+ModelCatalogServiceCreateLogicalModelProcedure,
			connect.WithSchema(modelCatalogServiceMethods.ByName("CreateLogicalModel")),
			connect.WithClientOptions(opts...),
		),
		getLogicalModel: connect.NewClient[v1.GetLogicalModelRequest, v1.GetLogicalModelResponse](
			httpClient,
			baseURL+ModelCatalogServiceGetLogicalModelProcedure,
			connect.WithSchema(modelCatalogServiceMethods.ByName("GetLogicalModel")),
			connect.WithClientOptions(opts...),
		),
		listLogicalModels: connect.NewClient[v1.ListLogicalModelsRequest, v1.ListLogicalModelsResponse](
			httpClient,
			baseURL+ModelCatalogServiceListLogicalModelsProcedure,
			connect.WithSchema(modelCatalogServiceMethods.ByName("ListLogicalModels")),
			connect.WithClientOptions(opts...),
		),
		updateLogicalModel: connect.NewClient[v1.UpdateLogicalModelRequest, v1.UpdateLogicalModelResponse](
			httpClient,
			baseURL+ModelCatalogServiceUpdateLogicalModelProcedure,
			connect.WithSchema(modelCatalogServiceMethods.ByName("UpdateLogicalModel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelCatalogServiceClient implements ModelCatalogServiceClient.
type modelCatalogServiceClient struct {
	createLogicalModel *connect.Client[v1.CreateLogicalModelRequest, v1.CreateLogicalModelResponse]
	getLogicalModel    *connect.Client[v1.GetLogicalModelRequest, v1.GetLogicalModelResponse]
	listLogicalModels  *connect.Client[v1.ListLogicalModelsRequest, v1.ListLogicalModelsResponse]
	updateLogicalModel *connect.Client[v1.UpdateLogicalModelRequest, v1.UpdateLogicalModelResponse]
}

// CreateLogicalModel calls llm.v1.ModelCatalogService.CreateLogicalModel.
func (c *modelCatalogServiceClient) CreateLogicalModel(ctx context.Context, req *connect.Request[v1.CreateLogicalModelRequest]) (*connect.Response[v1.CreateLogicalModelResponse], error) {
	return c.createLogicalModel.CallUnary(ctx, req)
}

// GetLogicalModel calls llm.v1.ModelCatalogService.GetLogicalModel.
func (c *modelCatalogServiceClient) GetLogicalModel(ctx context.Context, req *connect.Request[v1.GetLogicalModelRequest]) (*connect.Response[v1.GetLogicalModelResponse], error) {
	return c.getLogicalModel.CallUnary(ctx, req)
}

// ListLogicalModels calls llm.v1.ModelCatalogService.ListLogicalModels.
func (c *modelCatalogServiceClient) ListLogicalModels(ctx context.Context, req *connect.Request[v1.ListLogicalModelsRequest]) (*connect.Response[v1.ListLogicalModelsResponse], error) {
	return c.listLogicalModels.CallUnary(ctx, req)
}

// UpdateLogicalModel calls llm.v1.ModelCatalogService.UpdateLogicalModel.
func (c *modelCatalogServiceClient) UpdateLogicalModel(ctx context.Context, req *connect.Request[v1.UpdateLogicalModelRequest]) (*connect.Response[v1.UpdateLogicalModelResponse], error) {
	return c.updateLogicalModel.CallUnary(ctx, req)
}

// ModelCatalogServiceHandler is an implementation of the llm.v1.ModelCatalogService service.
type ModelCatalogServiceHandler interface {
	CreateLogicalModel(context.Context, *connect.Request[v1.CreateLogicalModelRequest]) (*connect.Response[v1.CreateLogicalModelResponse], error)
	GetLogicalModel(context.Context, *connect.Request[v1.GetLogicalModelRequest]) (*connect.Response[v1.GetLogicalModelResponse], error)
	ListLogicalModels(context.Context, *connect.Request[v1.ListLogicalModelsRequest]) (*connect.Response[v1.ListLogicalModelsResponse], error)
	UpdateLogicalModel(context.Context, *connect.Request[v1.UpdateLogicalModelRequest]) (*connect.Response[v1.UpdateLogicalModelResponse], error)
}

// NewModelCatalogServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelCatalogServiceHandler(svc ModelCatalogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelCatalogServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("ModelCatalogService").Methods()
	modelCatalogServiceCreateLogicalModelHandler := connect.NewUnaryHandler(
		ModelCatalogServiceCreateLogicalModelProcedure,
		svc.CreateLogicalModel,
		connect.WithSchema(modelCatalogServiceMethods.ByName("CreateLogicalModel")),
		connect.WithHandlerOptions(opts...),
	)
	modelCatalogServiceGetLogicalModelHandler := connect.NewUnaryHandler(
		ModelCatalogServiceGetLogicalModelProcedure,
		svc.GetLogicalModel,
		connect.WithSchema(modelCatalogServiceMethods.ByName("GetLogicalModel")),
		connect.WithHandlerOptions(opts...),
	)
	modelCatalogServiceListLogicalModelsHandler := connect.NewUnaryHandler(
		ModelCatalogServiceListLogicalModelsProcedure,
		svc.ListLogicalModels,
		connect.WithSchema(modelCatalogServiceMethods.ByName("ListLogicalModels")),
		connect.WithHandlerOptions(opts...),
	)
	modelCatalogServiceUpdateLogicalModelHandler := connect.NewUnaryHandler(
		ModelCatalogServiceUpdateLogicalModelProcedure,
		svc.UpdateLogicalModel,
		connect.WithSchema(modelCatalogServiceMethods.ByName("UpdateLogicalModel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.ModelCatalogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelCatalogServiceCreateLogicalModelProcedure:
			modelCatalogServiceCreateLogicalModelHandler.ServeHTTP(w, r)
		case ModelCatalogServiceGetLogicalModelProcedure:
			modelCatalogServiceGetLogicalModelHandler.ServeHTTP(w, r)
		case ModelCatalogServiceListLogicalModelsProcedure:
			modelCatalogServiceListLogicalModelsHandler.ServeHTTP(w, r)
		case ModelCatalogServiceUpdateLogicalModelProcedure:
			modelCatalogServiceUpdateLogicalModelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelCatalogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelCatalogServiceHandler struct{}

func (UnimplementedModelCatalogServiceHandler) CreateLogicalModel(context.Context, *connect.Request[v1.CreateLogicalModelRequest]) (*connect.Response[v1.CreateLogicalModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ModelCatalogService.CreateLogicalModel is not implemented"))
}

func (UnimplementedModelCatalogServiceHandler) GetLogicalModel(context.Context, *connect.Request[v1.GetLogicalModelRequest]) (*connect.Response[v1.GetLogicalModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ModelCatalogService.GetLogicalModel is not implemented"))
}

func (UnimplementedModelCatalogServiceHandler) ListLogicalModels(context.Context, *connect.Request[v1.ListLogicalModelsRequest]) (*connect.Response[v1.ListLogicalModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ModelCatalogService.ListLogicalModels is not implemented"))
}

func (UnimplementedModelCatalogServiceHandler) UpdateLogicalModel(context.Context, *connect.Request[v1.UpdateLogicalModelRequest]) (*connect.Response[v1.UpdateLogicalModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.ModelCatalogService.UpdateLogicalModel is not implemented"))
}

// RoutingPolicyServiceClient is a client for the llm.v1.RoutingPolicyService service.
type RoutingPolicyServiceClient interface {
	CreateRoutingPolicy(context.Context, *connect.Request[v1.CreateRoutingPolicyRequest]) (*connect.Response[v1.CreateRoutingPolicyResponse], error)
	GetRoutingPolicy(context.Context, *connect.Request[v1.GetRoutingPolicyRequest]) (*connect.Response[v1.GetRoutingPolicyResponse], error)
	ListRoutingPolicies(context.Context, *connect.Request[v1.ListRoutingPoliciesRequest]) (*connect.Response[v1.ListRoutingPoliciesResponse], error)
	UpdateRoutingPolicy(context.Context, *connect.Request[v1.UpdateRoutingPolicyRequest]) (*connect.Response[v1.UpdateRoutingPolicyResponse], error)
}

// NewRoutingPolicyServiceClient constructs a client for the llm.v1.RoutingPolicyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoutingPolicyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoutingPolicyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	routingPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("RoutingPolicyService").Methods()
	return &routingPolicyServiceClient{
		createRoutingPolicy: connect.NewClient[v1.CreateRoutingPolicyRequest, v1.CreateRoutingPolicyResponse](
			httpClient,
			baseURL+RoutingPolicyServiceCreateRoutingPolicyProcedure,
			connect.WithSchema(routingPolicyServiceMethods.ByName("CreateRoutingPolicy")),
			connect.WithClientOptions(opts...),
		),
		getRoutingPolicy: connect.NewClient[v1.GetRoutingPolicyRequest, v1.GetRoutingPolicyResponse](
			httpClient,
			baseURL+RoutingPolicyServiceGetRoutingPolicyProcedure,
			connect.WithSchema(routingPolicyServiceMethods.ByName("GetRoutingPolicy")),
			connect.WithClientOptions(opts...),
		),
		listRoutingPolicies: connect.NewClient[v1.ListRoutingPoliciesRequest, v1.ListRoutingPoliciesResponse](
			httpClient,
			baseURL+RoutingPolicyServiceListRoutingPoliciesProcedure,
			connect.WithSchema(routingPolicyServiceMethods.ByName("ListRoutingPolicies")),
			connect.WithClientOptions(opts...),
		),
		updateRoutingPolicy: connect.NewClient[v1.UpdateRoutingPolicyRequest, v1.UpdateRoutingPolicyResponse](
			httpClient,
			baseURL+RoutingPolicyServiceUpdateRoutingPolicyProcedure,
			connect.WithSchema(routingPolicyServiceMethods.ByName("UpdateRoutingPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// routingPolicyServiceClient implements RoutingPolicyServiceClient.
type routingPolicyServiceClient struct {
	createRoutingPolicy *connect.Client[v1.CreateRoutingPolicyRequest, v1.CreateRoutingPolicyResponse]
	getRoutingPolicy    *connect.Client[v1.GetRoutingPolicyRequest, v1.GetRoutingPolicyResponse]
	listRoutingPolicies *connect.Client[v1.ListRoutingPoliciesRequest, v1.ListRoutingPoliciesResponse]
	updateRoutingPolicy *connect.Client[v1.UpdateRoutingPolicyRequest, v1.UpdateRoutingPolicyResponse]
}

// CreateRoutingPolicy calls llm.v1.RoutingPolicyService.CreateRoutingPolicy.
func (c *routingPolicyServiceClient) CreateRoutingPolicy(ctx context.Context, req *connect.Request[v1.CreateRoutingPolicyRequest]) (*connect.Response[v1.CreateRoutingPolicyResponse], error) {
	return c.createRoutingPolicy.CallUnary(ctx, req)
}

// GetRoutingPolicy calls llm.v1.RoutingPolicyService.GetRoutingPolicy.
func (c *routingPolicyServiceClient) GetRoutingPolicy(ctx context.Context, req *connect.Request[v1.GetRoutingPolicyRequest]) (*connect.Response[v1.GetRoutingPolicyResponse], error) {
	return c.getRoutingPolicy.CallUnary(ctx, req)
}

// ListRoutingPolicies calls llm.v1.RoutingPolicyService.ListRoutingPolicies.
func (c *routingPolicyServiceClient) ListRoutingPolicies(ctx context.Context, req *connect.Request[v1.ListRoutingPoliciesRequest]) (*connect.Response[v1.ListRoutingPoliciesResponse], error) {
	return c.listRoutingPolicies.CallUnary(ctx, req)
}

// UpdateRoutingPolicy calls llm.v1.RoutingPolicyService.UpdateRoutingPolicy.
func (c *routingPolicyServiceClient) UpdateRoutingPolicy(ctx context.Context, req *connect.Request[v1.UpdateRoutingPolicyRequest]) (*connect.Response[v1.UpdateRoutingPolicyResponse], error) {
	return c.updateRoutingPolicy.CallUnary(ctx, req)
}

// RoutingPolicyServiceHandler is an implementation of the llm.v1.RoutingPolicyService service.
type RoutingPolicyServiceHandler interface {
	CreateRoutingPolicy(context.Context, *connect.Request[v1.CreateRoutingPolicyRequest]) (*connect.Response[v1.CreateRoutingPolicyResponse], error)
	GetRoutingPolicy(context.Context, *connect.Request[v1.GetRoutingPolicyRequest]) (*connect.Response[v1.GetRoutingPolicyResponse], error)
	ListRoutingPolicies(context.Context, *connect.Request[v1.ListRoutingPoliciesRequest]) (*connect.Response[v1.ListRoutingPoliciesResponse], error)
	UpdateRoutingPolicy(context.Context, *connect.Request[v1.UpdateRoutingPolicyRequest]) (*connect.Response[v1.UpdateRoutingPolicyResponse], error)
}

// NewRoutingPolicyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoutingPolicyServiceHandler(svc RoutingPolicyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	routingPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("RoutingPolicyService").Methods()
	routingPolicyServiceCreateRoutingPolicyHandler := connect.NewUnaryHandler(
		RoutingPolicyServiceCreateRoutingPolicyProcedure,
		svc.CreateRoutingPolicy,
		connect.WithSchema(routingPolicyServiceMethods.ByName("CreateRoutingPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	routingPolicyServiceGetRoutingPolicyHandler := connect.NewUnaryHandler(
		RoutingPolicyServiceGetRoutingPolicyProcedure,
		svc.GetRoutingPolicy,
		connect.WithSchema(routingPolicyServiceMethods.ByName("GetRoutingPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	routingPolicyServiceListRoutingPoliciesHandler := connect.NewUnaryHandler(
		RoutingPolicyServiceListRoutingPoliciesProcedure,
		svc.ListRoutingPolicies,
		connect.WithSchema(routingPolicyServiceMethods.ByName("ListRoutingPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	routingPolicyServiceUpdateRoutingPolicyHandler := connect.NewUnaryHandler(
		RoutingPolicyServiceUpdateRoutingPolicyProcedure,
		svc.UpdateRoutingPolicy,
		connect.WithSchema(routingPolicyServiceMethods.ByName("UpdateRoutingPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.RoutingPolicyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoutingPolicyServiceCreateRoutingPolicyProcedure:
			routingPolicyServiceCreateRoutingPolicyHandler.ServeHTTP(w, r)
		case RoutingPolicyServiceGetRoutingPolicyProcedure:
			routingPolicyServiceGetRoutingPolicyHandler.ServeHTTP(w, r)
		case RoutingPolicyServiceListRoutingPoliciesProcedure:
			routingPolicyServiceListRoutingPoliciesHandler.ServeHTTP(w, r)
		case RoutingPolicyServiceUpdateRoutingPolicyProcedure:
			routingPolicyServiceUpdateRoutingPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoutingPolicyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoutingPolicyServiceHandler struct{}

func (UnimplementedRoutingPolicyServiceHandler) CreateRoutingPolicy(context.Context, *connect.Request[v1.CreateRoutingPolicyRequest]) (*connect.Response[v1.CreateRoutingPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.RoutingPolicyService.CreateRoutingPolicy is not implemented"))
}

func (UnimplementedRoutingPolicyServiceHandler) GetRoutingPolicy(context.Context, *connect.Request[v1.GetRoutingPolicyRequest]) (*connect.Response[v1.GetRoutingPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.RoutingPolicyService.GetRoutingPolicy is not implemented"))
}

func (UnimplementedRoutingPolicyServiceHandler) ListRoutingPolicies(context.Context, *connect.Request[v1.ListRoutingPoliciesRequest]) (*connect.Response[v1.ListRoutingPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.RoutingPolicyService.ListRoutingPolicies is not implemented"))
}

func (UnimplementedRoutingPolicyServiceHandler) UpdateRoutingPolicy(context.Context, *connect.Request[v1.UpdateRoutingPolicyRequest]) (*connect.Response[v1.UpdateRoutingPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.RoutingPolicyService.UpdateRoutingPolicy is not implemented"))
}

// QuotaPolicyServiceClient is a client for the llm.v1.QuotaPolicyService service.
type QuotaPolicyServiceClient interface {
	CreateQuotaPolicy(context.Context, *connect.Request[v1.CreateQuotaPolicyRequest]) (*connect.Response[v1.CreateQuotaPolicyResponse], error)
	GetQuotaPolicy(context.Context, *connect.Request[v1.GetQuotaPolicyRequest]) (*connect.Response[v1.GetQuotaPolicyResponse], error)
	ListQuotaPolicies(context.Context, *connect.Request[v1.ListQuotaPoliciesRequest]) (*connect.Response[v1.ListQuotaPoliciesResponse], error)
	UpdateQuotaPolicy(context.Context, *connect.Request[v1.UpdateQuotaPolicyRequest]) (*connect.Response[v1.UpdateQuotaPolicyResponse], error)
}

// NewQuotaPolicyServiceClient constructs a client for the llm.v1.QuotaPolicyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQuotaPolicyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QuotaPolicyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	quotaPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("QuotaPolicyService").Methods()
	return &quotaPolicyServiceClient{
		createQuotaPolicy: connect.NewClient[v1.CreateQuotaPolicyRequest, v1.CreateQuotaPolicyResponse](
			httpClient,
			baseURL+QuotaPolicyServiceCreateQuotaPolicyProcedure,
			connect.WithSchema(quotaPolicyServiceMethods.ByName("CreateQuotaPolicy")),
			connect.WithClientOptions(opts...),
		),
		getQuotaPolicy: connect.NewClient[v1.GetQuotaPolicyRequest, v1.GetQuotaPolicyResponse](
			httpClient,
			baseURL+QuotaPolicyServiceGetQuotaPolicyProcedure,
			connect.WithSchema(quotaPolicyServiceMethods.ByName("GetQuotaPolicy")),
			connect.WithClientOptions(opts...),
		),
		listQuotaPolicies: connect.NewClient[v1.ListQuotaPoliciesRequest, v1.ListQuotaPoliciesResponse](
			httpClient,
			baseURL+QuotaPolicyServiceListQuotaPoliciesProcedure,
			connect.WithSchema(quotaPolicyServiceMethods.ByName("ListQuotaPolicies")),
			connect.WithClientOptions(opts...),
		),
		updateQuotaPolicy: connect.NewClient[v1.UpdateQuotaPolicyRequest, v1.UpdateQuotaPolicyResponse](
			httpClient,
			baseURL+QuotaPolicyServiceUpdateQuotaPolicyProcedure,
			connect.WithSchema(quotaPolicyServiceMethods.ByName("UpdateQuotaPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// quotaPolicyServiceClient implements QuotaPolicyServiceClient.
type quotaPolicyServiceClient struct {
	createQuotaPolicy *connect.Client[v1.CreateQuotaPolicyRequest, v1.CreateQuotaPolicyResponse]
	getQuotaPolicy    *connect.Client[v1.GetQuotaPolicyRequest, v1.GetQuotaPolicyResponse]
	listQuotaPolicies *connect.Client[v1.ListQuotaPoliciesRequest, v1.ListQuotaPoliciesResponse]
	updateQuotaPolicy *connect.Client[v1.UpdateQuotaPolicyRequest, v1.UpdateQuotaPolicyResponse]
}

// CreateQuotaPolicy calls llm.v1.QuotaPolicyService.CreateQuotaPolicy.
func (c *quotaPolicyServiceClient) CreateQuotaPolicy(ctx context.Context, req *connect.Request[v1.CreateQuotaPolicyRequest]) (*connect.Response[v1.CreateQuotaPolicyResponse], error) {
	return c.createQuotaPolicy.CallUnary(ctx, req)
}

// GetQuotaPolicy calls llm.v1.QuotaPolicyService.GetQuotaPolicy.
func (c *quotaPolicyServiceClient) GetQuotaPolicy(ctx context.Context, req *connect.Request[v1.GetQuotaPolicyRequest]) (*connect.Response[v1.GetQuotaPolicyResponse], error) {
	return c.getQuotaPolicy.CallUnary(ctx, req)
}

// ListQuotaPolicies calls llm.v1.QuotaPolicyService.ListQuotaPolicies.
func (c *quotaPolicyServiceClient) ListQuotaPolicies(ctx context.Context, req *connect.Request[v1.ListQuotaPoliciesRequest]) (*connect.Response[v1.ListQuotaPoliciesResponse], error) {
	return c.listQuotaPolicies.CallUnary(ctx, req)
}

// UpdateQuotaPolicy calls llm.v1.QuotaPolicyService.UpdateQuotaPolicy.
func (c *quotaPolicyServiceClient) UpdateQuotaPolicy(ctx context.Context, req *connect.Request[v1.UpdateQuotaPolicyRequest]) (*connect.Response[v1.UpdateQuotaPolicyResponse], error) {
	return c.updateQuotaPolicy.CallUnary(ctx, req)
}

// QuotaPolicyServiceHandler is an implementation of the llm.v1.QuotaPolicyService service.
type QuotaPolicyServiceHandler interface {
	CreateQuotaPolicy(context.Context, *connect.Request[v1.CreateQuotaPolicyRequest]) (*connect.Response[v1.CreateQuotaPolicyResponse], error)
	GetQuotaPolicy(context.Context, *connect.Request[v1.GetQuotaPolicyRequest]) (*connect.Response[v1.GetQuotaPolicyResponse], error)
	ListQuotaPolicies(context.Context, *connect.Request[v1.ListQuotaPoliciesRequest]) (*connect.Response[v1.ListQuotaPoliciesResponse], error)
	UpdateQuotaPolicy(context.Context, *connect.Request[v1.UpdateQuotaPolicyRequest]) (*connect.Response[v1.UpdateQuotaPolicyResponse], error)
}

// NewQuotaPolicyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQuotaPolicyServiceHandler(svc QuotaPolicyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	quotaPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("QuotaPolicyService").Methods()
	quotaPolicyServiceCreateQuotaPolicyHandler := connect.NewUnaryHandler(
		QuotaPolicyServiceCreateQuotaPolicyProcedure,
		svc.CreateQuotaPolicy,
		connect.WithSchema(quotaPolicyServiceMethods.ByName("CreateQuotaPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	quotaPolicyServiceGetQuotaPolicyHandler := connect.NewUnaryHandler(
		QuotaPolicyServiceGetQuotaPolicyProcedure,
		svc.GetQuotaPolicy,
		connect.WithSchema(quotaPolicyServiceMethods.ByName("GetQuotaPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	quotaPolicyServiceListQuotaPoliciesHandler := connect.NewUnaryHandler(
		QuotaPolicyServiceListQuotaPoliciesProcedure,
		svc.ListQuotaPolicies,
		connect.WithSchema(quotaPolicyServiceMethods.ByName("ListQuotaPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	quotaPolicyServiceUpdateQuotaPolicyHandler := connect.NewUnaryHandler(
		QuotaPolicyServiceUpdateQuotaPolicyProcedure,
		svc.UpdateQuotaPolicy,
		connect.WithSchema(quotaPolicyServiceMethods.ByName("UpdateQuotaPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.QuotaPolicyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QuotaPolicyServiceCreateQuotaPolicyProcedure:
			quotaPolicyServiceCreateQuotaPolicyHandler.ServeHTTP(w, r)
		case QuotaPolicyServiceGetQuotaPolicyProcedure:
			quotaPolicyServiceGetQuotaPolicyHandler.ServeHTTP(w, r)
		case QuotaPolicyServiceListQuotaPoliciesProcedure:
			quotaPolicyServiceListQuotaPoliciesHandler.ServeHTTP(w, r)
		case QuotaPolicyServiceUpdateQuotaPolicyProcedure:
			quotaPolicyServiceUpdateQuotaPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQuotaPolicyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQuotaPolicyServiceHandler struct{}

func (UnimplementedQuotaPolicyServiceHandler) CreateQuotaPolicy(context.Context, *connect.Request[v1.CreateQuotaPolicyRequest]) (*connect.Response[v1.CreateQuotaPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.QuotaPolicyService.CreateQuotaPolicy is not implemented"))
}

func (UnimplementedQuotaPolicyServiceHandler) GetQuotaPolicy(context.Context, *connect.Request[v1.GetQuotaPolicyRequest]) (*connect.Response[v1.GetQuotaPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.QuotaPolicyService.GetQuotaPolicy is not implemented"))
}

func (UnimplementedQuotaPolicyServiceHandler) ListQuotaPolicies(context.Context, *connect.Request[v1.ListQuotaPoliciesRequest]) (*connect.Response[v1.ListQuotaPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.QuotaPolicyService.ListQuotaPolicies is not implemented"))
}

func (UnimplementedQuotaPolicyServiceHandler) UpdateQuotaPolicy(context.Context, *connect.Request[v1.UpdateQuotaPolicyRequest]) (*connect.Response[v1.UpdateQuotaPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.QuotaPolicyService.UpdateQuotaPolicy is not implemented"))
}

// SpendPolicyServiceClient is a client for the llm.v1.SpendPolicyService service.
type SpendPolicyServiceClient interface {
	CreateSpendPolicy(context.Context, *connect.Request[v1.CreateSpendPolicyRequest]) (*connect.Response[v1.CreateSpendPolicyResponse], error)
	GetSpendPolicy(context.Context, *connect.Request[v1.GetSpendPolicyRequest]) (*connect.Response[v1.GetSpendPolicyResponse], error)
	ListSpendPolicies(context.Context, *connect.Request[v1.ListSpendPoliciesRequest]) (*connect.Response[v1.ListSpendPoliciesResponse], error)
	UpdateSpendPolicy(context.Context, *connect.Request[v1.UpdateSpendPolicyRequest]) (*connect.Response[v1.UpdateSpendPolicyResponse], error)
}

// NewSpendPolicyServiceClient constructs a client for the llm.v1.SpendPolicyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSpendPolicyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SpendPolicyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	spendPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("SpendPolicyService").Methods()
	return &spendPolicyServiceClient{
		createSpendPolicy: connect.NewClient[v1.CreateSpendPolicyRequest, v1.CreateSpendPolicyResponse](
			httpClient,
			baseURL+SpendPolicyServiceCreateSpendPolicyProcedure,
			connect.WithSchema(spendPolicyServiceMethods.ByName("CreateSpendPolicy")),
			connect.WithClientOptions(opts...),
		),
		getSpendPolicy: connect.NewClient[v1.GetSpendPolicyRequest, v1.GetSpendPolicyResponse](
			httpClient,
			baseURL+SpendPolicyServiceGetSpendPolicyProcedure,
			connect.WithSchema(spendPolicyServiceMethods.ByName("GetSpendPolicy")),
			connect.WithClientOptions(opts...),
		),
		listSpendPolicies: connect.NewClient[v1.ListSpendPoliciesRequest, v1.ListSpendPoliciesResponse](
			httpClient,
			baseURL+SpendPolicyServiceListSpendPoliciesProcedure,
			connect.WithSchema(spendPolicyServiceMethods.ByName("ListSpendPolicies")),
			connect.WithClientOptions(opts...),
		),
		updateSpendPolicy: connect.NewClient[v1.UpdateSpendPolicyRequest, v1.UpdateSpendPolicyResponse](
			httpClient,
			baseURL+SpendPolicyServiceUpdateSpendPolicyProcedure,
			connect.WithSchema(spendPolicyServiceMethods.ByName("UpdateSpendPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// spendPolicyServiceClient implements SpendPolicyServiceClient.
type spendPolicyServiceClient struct {
	createSpendPolicy *connect.Client[v1.CreateSpendPolicyRequest, v1.CreateSpendPolicyResponse]
	getSpendPolicy    *connect.Client[v1.GetSpendPolicyRequest, v1.GetSpendPolicyResponse]
	listSpendPolicies *connect.Client[v1.ListSpendPoliciesRequest, v1.ListSpendPoliciesResponse]
	updateSpendPolicy *connect.Client[v1.UpdateSpendPolicyRequest, v1.UpdateSpendPolicyResponse]
}

// CreateSpendPolicy calls llm.v1.SpendPolicyService.CreateSpendPolicy.
func (c *spendPolicyServiceClient) CreateSpendPolicy(ctx context.Context, req *connect.Request[v1.CreateSpendPolicyRequest]) (*connect.Response[v1.CreateSpendPolicyResponse], error) {
	return c.createSpendPolicy.CallUnary(ctx, req)
}

// GetSpendPolicy calls llm.v1.SpendPolicyService.GetSpendPolicy.
func (c *spendPolicyServiceClient) GetSpendPolicy(ctx context.Context, req *connect.Request[v1.GetSpendPolicyRequest]) (*connect.Response[v1.GetSpendPolicyResponse], error) {
	return c.getSpendPolicy.CallUnary(ctx, req)
}

// ListSpendPolicies calls llm.v1.SpendPolicyService.ListSpendPolicies.
func (c *spendPolicyServiceClient) ListSpendPolicies(ctx context.Context, req *connect.Request[v1.ListSpendPoliciesRequest]) (*connect.Response[v1.ListSpendPoliciesResponse], error) {
	return c.listSpendPolicies.CallUnary(ctx, req)
}

// UpdateSpendPolicy calls llm.v1.SpendPolicyService.UpdateSpendPolicy.
func (c *spendPolicyServiceClient) UpdateSpendPolicy(ctx context.Context, req *connect.Request[v1.UpdateSpendPolicyRequest]) (*connect.Response[v1.UpdateSpendPolicyResponse], error) {
	return c.updateSpendPolicy.CallUnary(ctx, req)
}

// SpendPolicyServiceHandler is an implementation of the llm.v1.SpendPolicyService service.
type SpendPolicyServiceHandler interface {
	CreateSpendPolicy(context.Context, *connect.Request[v1.CreateSpendPolicyRequest]) (*connect.Response[v1.CreateSpendPolicyResponse], error)
	GetSpendPolicy(context.Context, *connect.Request[v1.GetSpendPolicyRequest]) (*connect.Response[v1.GetSpendPolicyResponse], error)
	ListSpendPolicies(context.Context, *connect.Request[v1.ListSpendPoliciesRequest]) (*connect.Response[v1.ListSpendPoliciesResponse], error)
	UpdateSpendPolicy(context.Context, *connect.Request[v1.UpdateSpendPolicyRequest]) (*connect.Response[v1.UpdateSpendPolicyResponse], error)
}

// NewSpendPolicyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSpendPolicyServiceHandler(svc SpendPolicyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	spendPolicyServiceMethods := v1.File_llm_v1_vendor_service_proto.Services().ByName("SpendPolicyService").Methods()
	spendPolicyServiceCreateSpendPolicyHandler := connect.NewUnaryHandler(
		SpendPolicyServiceCreateSpendPolicyProcedure,
		svc.CreateSpendPolicy,
		connect.WithSchema(spendPolicyServiceMethods.ByName("CreateSpendPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	spendPolicyServiceGetSpendPolicyHandler := connect.NewUnaryHandler(
		SpendPolicyServiceGetSpendPolicyProcedure,
		svc.GetSpendPolicy,
		connect.WithSchema(spendPolicyServiceMethods.ByName("GetSpendPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	spendPolicyServiceListSpendPoliciesHandler := connect.NewUnaryHandler(
		SpendPolicyServiceListSpendPoliciesProcedure,
		svc.ListSpendPolicies,
		connect.WithSchema(spendPolicyServiceMethods.ByName("ListSpendPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	spendPolicyServiceUpdateSpendPolicyHandler := connect.NewUnaryHandler(
		SpendPolicyServiceUpdateSpendPolicyProcedure,
		svc.UpdateSpendPolicy,
		connect.WithSchema(spendPolicyServiceMethods.ByName("UpdateSpendPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llm.v1.SpendPolicyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SpendPolicyServiceCreateSpendPolicyProcedure:
			spendPolicyServiceCreateSpendPolicyHandler.ServeHTTP(w, r)
		case SpendPolicyServiceGetSpendPolicyProcedure:
			spendPolicyServiceGetSpendPolicyHandler.ServeHTTP(w, r)
		case SpendPolicyServiceListSpendPoliciesProcedure:
			spendPolicyServiceListSpendPoliciesHandler.ServeHTTP(w, r)
		case SpendPolicyServiceUpdateSpendPolicyProcedure:
			spendPolicyServiceUpdateSpendPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSpendPolicyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSpendPolicyServiceHandler struct{}

func (UnimplementedSpendPolicyServiceHandler) CreateSpendPolicy(context.Context, *connect.Request[v1.CreateSpendPolicyRequest]) (*connect.Response[v1.CreateSpendPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.SpendPolicyService.CreateSpendPolicy is not implemented"))
}

func (UnimplementedSpendPolicyServiceHandler) GetSpendPolicy(context.Context, *connect.Request[v1.GetSpendPolicyRequest]) (*connect.Response[v1.GetSpendPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.SpendPolicyService.GetSpendPolicy is not implemented"))
}

func (UnimplementedSpendPolicyServiceHandler) ListSpendPolicies(context.Context, *connect.Request[v1.ListSpendPoliciesRequest]) (*connect.Response[v1.ListSpendPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.SpendPolicyService.ListSpendPolicies is not implemented"))
}

func (UnimplementedSpendPolicyServiceHandler) UpdateSpendPolicy(context.Context, *connect.Request[v1.UpdateSpendPolicyRequest]) (*connect.Response[v1.UpdateSpendPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llm.v1.SpendPolicyService.UpdateSpendPolicy is not implemented"))
}
