// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: llm/v1/audit_service.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_ListAuditEvents_FullMethodName = "/llm.v1.AuditService/ListAuditEvents"
	AuditService_GetRequestTrace_FullMethodName = "/llm.v1.AuditService/GetRequestTrace"
	AuditService_CreateExportJob_FullMethodName = "/llm.v1.AuditService/CreateExportJob"
	AuditService_GetExportJob_FullMethodName    = "/llm.v1.AuditService/GetExportJob"
	AuditService_ListExportJobs_FullMethodName  = "/llm.v1.AuditService/ListExportJobs"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	GetRequestTrace(ctx context.Context, in *GetRequestTraceRequest, opts ...grpc.CallOption) (*GetRequestTraceResponse, error)
	CreateExportJob(ctx context.Context, in *CreateExportJobRequest, opts ...grpc.CallOption) (*CreateExportJobResponse, error)
	GetExportJob(ctx context.Context, in *GetExportJobRequest, opts ...grpc.CallOption) (*GetExportJobResponse, error)
	ListExportJobs(ctx context.Context, in *ListExportJobsRequest, opts ...grpc.CallOption) (*ListExportJobsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetRequestTrace(ctx context.Context, in *GetRequestTraceRequest, opts ...grpc.CallOption) (*GetRequestTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestTraceResponse)
	err := c.cc.Invoke(ctx, AuditService_GetRequestTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) CreateExportJob(ctx context.Context, in *CreateExportJobRequest, opts ...grpc.CallOption) (*CreateExportJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExportJobResponse)
	err := c.cc.Invoke(ctx, AuditService_CreateExportJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetExportJob(ctx context.Context, in *GetExportJobRequest, opts ...grpc.CallOption) (*GetExportJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportJobResponse)
	err := c.cc.Invoke(ctx, AuditService_GetExportJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListExportJobs(ctx context.Context, in *ListExportJobsRequest, opts ...grpc.CallOption) (*ListExportJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExportJobsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListExportJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error)
	GetRequestTrace(context.Context, *GetRequestTraceRequest) (*GetRequestTraceResponse, error)
	CreateExportJob(context.Context, *CreateExportJobRequest) (*CreateExportJobResponse, error)
	GetExportJob(context.Context, *GetExportJobRequest) (*GetExportJobResponse, error)
	ListExportJobs(context.Context, *ListExportJobsRequest) (*ListExportJobsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEvents not implemented")
}
func (UnimplementedAuditServiceServer) GetRequestTrace(context.Context, *GetRequestTraceRequest) (*GetRequestTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequestTrace not implemented")
}
func (UnimplementedAuditServiceServer) CreateExportJob(context.Context, *CreateExportJobRequest) (*CreateExportJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExportJob not implemented")
}
func (UnimplementedAuditServiceServer) GetExportJob(context.Context, *GetExportJobRequest) (*GetExportJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportJob not implemented")
}
func (UnimplementedAuditServiceServer) ListExportJobs(context.Context, *ListExportJobsRequest) (*ListExportJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExportJobs not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_ListAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditEvents(ctx, req.(*ListAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetRequestTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetRequestTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetRequestTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetRequestTrace(ctx, req.(*GetRequestTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_CreateExportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).CreateExportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_CreateExportJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).CreateExportJob(ctx, req.(*CreateExportJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetExportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetExportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetExportJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetExportJob(ctx, req.(*GetExportJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListExportJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExportJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListExportJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListExportJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListExportJobs(ctx, req.(*ListExportJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAuditEvents",
			Handler:    _AuditService_ListAuditEvents_Handler,
		},
		{
			MethodName: "GetRequestTrace",
			Handler:    _AuditService_GetRequestTrace_Handler,
		},
		{
			MethodName: "CreateExportJob",
			Handler:    _AuditService_CreateExportJob_Handler,
		},
		{
			MethodName: "GetExportJob",
			Handler:    _AuditService_GetExportJob_Handler,
		},
		{
			MethodName: "ListExportJobs",
			Handler:    _AuditService_ListExportJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/audit_service.proto",
}
