// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: llm/v1/audit_service.proto

package llmv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuditEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuditEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuditEventMultiError, or
// nil if none found.
func (m *AuditEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for ActorId

	// no validation rules for ActorType

	// no validation rules for Action

	// no validation rules for Outcome

	// no validation rules for TargetResourceType

	// no validation rules for TargetResourceId

	// no validation rules for RequestId

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetOccurredAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "OccurredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "OccurredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOccurredAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "OccurredAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuditEventMultiError(errors)
	}

	return nil
}

// AuditEventMultiError is an error wrapping multiple validation errors
// returned by AuditEvent.ValidateAll() if the designated constraints aren't met.
type AuditEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditEventMultiError) AllErrors() []error { return m }

// AuditEventValidationError is the validation error returned by
// AuditEvent.Validate if the designated constraints aren't met.
type AuditEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditEventValidationError) ErrorName() string { return "AuditEventValidationError" }

// Error satisfies the builtin error interface
func (e AuditEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditEventValidationError{}

// Validate checks the field values on RequestTrace with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RequestTrace) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestTrace with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RequestTraceMultiError, or
// nil if none found.
func (m *RequestTrace) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestTrace) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for GatewayKeyId

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	// no validation rules for UpstreamModel

	// no validation rules for Status

	// no validation rules for FailureCategory

	// no validation rules for FailureMessage

	// no validation rules for LatencyMs

	// no validation rules for TotalTokens

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RequestTraceValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RequestTraceValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RequestTraceValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RequestTraceValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RequestTraceMultiError(errors)
	}

	return nil
}

// RequestTraceMultiError is an error wrapping multiple validation errors
// returned by RequestTrace.ValidateAll() if the designated constraints aren't met.
type RequestTraceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestTraceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestTraceMultiError) AllErrors() []error { return m }

// RequestTraceValidationError is the validation error returned by
// RequestTrace.Validate if the designated constraints aren't met.
type RequestTraceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestTraceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestTraceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestTraceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestTraceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestTraceValidationError) ErrorName() string { return "RequestTraceValidationError" }

// Error satisfies the builtin error interface
func (e RequestTraceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestTrace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestTraceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestTraceValidationError{}

// Validate checks the field values on ExportJob with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExportJob) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportJob with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExportJobMultiError, or nil
// if none found.
func (m *ExportJob) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportJob) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for Dataset

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExportJobValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	// no validation rules for DownloadUrl

	// no validation rules for Format

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExportJobValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAuditInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "AuditInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExportJobValidationError{
					field:  "AuditInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuditInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExportJobValidationError{
				field:  "AuditInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExportJobMultiError(errors)
	}

	return nil
}

// ExportJobMultiError is an error wrapping multiple validation errors returned
// by ExportJob.ValidateAll() if the designated constraints aren't met.
type ExportJobMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportJobMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportJobMultiError) AllErrors() []error { return m }

// ExportJobValidationError is the validation error returned by
// ExportJob.Validate if the designated constraints aren't met.
type ExportJobValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportJobValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportJobValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportJobValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportJobValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportJobValidationError) ErrorName() string { return "ExportJobValidationError" }

// Error satisfies the builtin error interface
func (e ExportJobValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportJob.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportJobValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportJobValidationError{}

// Validate checks the field values on ListAuditEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAuditEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAuditEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAuditEventsRequestMultiError, or nil if none found.
func (m *ListAuditEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAuditEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for ActorId

	// no validation rules for TargetResourceType

	// no validation rules for TargetResourceId

	// no validation rules for Action

	// no validation rules for Outcome

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListAuditEventsRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListAuditEventsRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAuditEventsRequestValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListAuditEventsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListAuditEventsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAuditEventsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListAuditEventsRequestMultiError(errors)
	}

	return nil
}

// ListAuditEventsRequestMultiError is an error wrapping multiple validation
// errors returned by ListAuditEventsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAuditEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAuditEventsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAuditEventsRequestMultiError) AllErrors() []error { return m }

// ListAuditEventsRequestValidationError is the validation error returned by
// ListAuditEventsRequest.Validate if the designated constraints aren't met.
type ListAuditEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAuditEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAuditEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAuditEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAuditEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAuditEventsRequestValidationError) ErrorName() string {
	return "ListAuditEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAuditEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAuditEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAuditEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAuditEventsRequestValidationError{}

// Validate checks the field values on ListAuditEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAuditEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAuditEventsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAuditEventsResponseMultiError, or nil if none found.
func (m *ListAuditEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAuditEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAuditEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAuditEventsResponseValidationError{
						field:  fmt.Sprintf("AuditEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAuditEventsResponseValidationError{
						field:  fmt.Sprintf("AuditEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAuditEventsResponseValidationError{
					field:  fmt.Sprintf("AuditEvents[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListAuditEventsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListAuditEventsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAuditEventsResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListAuditEventsResponseMultiError(errors)
	}

	return nil
}

// ListAuditEventsResponseMultiError is an error wrapping multiple validation
// errors returned by ListAuditEventsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListAuditEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAuditEventsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAuditEventsResponseMultiError) AllErrors() []error { return m }

// ListAuditEventsResponseValidationError is the validation error returned by
// ListAuditEventsResponse.Validate if the designated constraints aren't met.
type ListAuditEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAuditEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAuditEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAuditEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAuditEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAuditEventsResponseValidationError) ErrorName() string {
	return "ListAuditEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAuditEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAuditEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAuditEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAuditEventsResponseValidationError{}

// Validate checks the field values on GetRequestTraceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRequestTraceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRequestTraceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRequestTraceRequestMultiError, or nil if none found.
func (m *GetRequestTraceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRequestTraceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	if len(errors) > 0 {
		return GetRequestTraceRequestMultiError(errors)
	}

	return nil
}

// GetRequestTraceRequestMultiError is an error wrapping multiple validation
// errors returned by GetRequestTraceRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRequestTraceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRequestTraceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRequestTraceRequestMultiError) AllErrors() []error { return m }

// GetRequestTraceRequestValidationError is the validation error returned by
// GetRequestTraceRequest.Validate if the designated constraints aren't met.
type GetRequestTraceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRequestTraceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRequestTraceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRequestTraceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRequestTraceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRequestTraceRequestValidationError) ErrorName() string {
	return "GetRequestTraceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRequestTraceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRequestTraceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRequestTraceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRequestTraceRequestValidationError{}

// Validate checks the field values on GetRequestTraceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRequestTraceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRequestTraceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRequestTraceResponseMultiError, or nil if none found.
func (m *GetRequestTraceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRequestTraceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRequestTrace()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRequestTraceResponseValidationError{
					field:  "RequestTrace",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRequestTraceResponseValidationError{
					field:  "RequestTrace",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRequestTrace()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRequestTraceResponseValidationError{
				field:  "RequestTrace",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRequestTraceResponseMultiError(errors)
	}

	return nil
}

// GetRequestTraceResponseMultiError is an error wrapping multiple validation
// errors returned by GetRequestTraceResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRequestTraceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRequestTraceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRequestTraceResponseMultiError) AllErrors() []error { return m }

// GetRequestTraceResponseValidationError is the validation error returned by
// GetRequestTraceResponse.Validate if the designated constraints aren't met.
type GetRequestTraceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRequestTraceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRequestTraceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRequestTraceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRequestTraceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRequestTraceResponseValidationError) ErrorName() string {
	return "GetRequestTraceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRequestTraceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRequestTraceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRequestTraceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRequestTraceResponseValidationError{}

// Validate checks the field values on CreateExportJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateExportJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateExportJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateExportJobRequestMultiError, or nil if none found.
func (m *CreateExportJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateExportJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExportJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateExportJobRequestValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateExportJobRequestValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExportJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateExportJobRequestValidationError{
				field:  "ExportJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateExportJobRequestMultiError(errors)
	}

	return nil
}

// CreateExportJobRequestMultiError is an error wrapping multiple validation
// errors returned by CreateExportJobRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateExportJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateExportJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateExportJobRequestMultiError) AllErrors() []error { return m }

// CreateExportJobRequestValidationError is the validation error returned by
// CreateExportJobRequest.Validate if the designated constraints aren't met.
type CreateExportJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateExportJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateExportJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateExportJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateExportJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateExportJobRequestValidationError) ErrorName() string {
	return "CreateExportJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateExportJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateExportJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateExportJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateExportJobRequestValidationError{}

// Validate checks the field values on CreateExportJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateExportJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateExportJobResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateExportJobResponseMultiError, or nil if none found.
func (m *CreateExportJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateExportJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExportJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateExportJobResponseValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateExportJobResponseValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExportJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateExportJobResponseValidationError{
				field:  "ExportJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateExportJobResponseMultiError(errors)
	}

	return nil
}

// CreateExportJobResponseMultiError is an error wrapping multiple validation
// errors returned by CreateExportJobResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateExportJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateExportJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateExportJobResponseMultiError) AllErrors() []error { return m }

// CreateExportJobResponseValidationError is the validation error returned by
// CreateExportJobResponse.Validate if the designated constraints aren't met.
type CreateExportJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateExportJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateExportJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateExportJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateExportJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateExportJobResponseValidationError) ErrorName() string {
	return "CreateExportJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateExportJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateExportJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateExportJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateExportJobResponseValidationError{}

// Validate checks the field values on GetExportJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExportJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExportJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExportJobRequestMultiError, or nil if none found.
func (m *GetExportJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExportJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExportJobId

	if len(errors) > 0 {
		return GetExportJobRequestMultiError(errors)
	}

	return nil
}

// GetExportJobRequestMultiError is an error wrapping multiple validation
// errors returned by GetExportJobRequest.ValidateAll() if the designated
// constraints aren't met.
type GetExportJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExportJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExportJobRequestMultiError) AllErrors() []error { return m }

// GetExportJobRequestValidationError is the validation error returned by
// GetExportJobRequest.Validate if the designated constraints aren't met.
type GetExportJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExportJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExportJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExportJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExportJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExportJobRequestValidationError) ErrorName() string {
	return "GetExportJobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetExportJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExportJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExportJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExportJobRequestValidationError{}

// Validate checks the field values on GetExportJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExportJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExportJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExportJobResponseMultiError, or nil if none found.
func (m *GetExportJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExportJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExportJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetExportJobResponseValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetExportJobResponseValidationError{
					field:  "ExportJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExportJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetExportJobResponseValidationError{
				field:  "ExportJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetExportJobResponseMultiError(errors)
	}

	return nil
}

// GetExportJobResponseMultiError is an error wrapping multiple validation
// errors returned by GetExportJobResponse.ValidateAll() if the designated
// constraints aren't met.
type GetExportJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExportJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExportJobResponseMultiError) AllErrors() []error { return m }

// GetExportJobResponseValidationError is the validation error returned by
// GetExportJobResponse.Validate if the designated constraints aren't met.
type GetExportJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExportJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExportJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExportJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExportJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExportJobResponseValidationError) ErrorName() string {
	return "GetExportJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetExportJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExportJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExportJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExportJobResponseValidationError{}

// Validate checks the field values on ListExportJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExportJobsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExportJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExportJobsRequestMultiError, or nil if none found.
func (m *ListExportJobsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExportJobsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for Dataset

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListExportJobsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListExportJobsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListExportJobsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListExportJobsRequestMultiError(errors)
	}

	return nil
}

// ListExportJobsRequestMultiError is an error wrapping multiple validation
// errors returned by ListExportJobsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListExportJobsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExportJobsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExportJobsRequestMultiError) AllErrors() []error { return m }

// ListExportJobsRequestValidationError is the validation error returned by
// ListExportJobsRequest.Validate if the designated constraints aren't met.
type ListExportJobsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExportJobsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExportJobsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExportJobsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExportJobsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExportJobsRequestValidationError) ErrorName() string {
	return "ListExportJobsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListExportJobsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExportJobsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExportJobsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExportJobsRequestValidationError{}

// Validate checks the field values on ListExportJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExportJobsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExportJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExportJobsResponseMultiError, or nil if none found.
func (m *ListExportJobsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExportJobsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExportJobs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListExportJobsResponseValidationError{
						field:  fmt.Sprintf("ExportJobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListExportJobsResponseValidationError{
						field:  fmt.Sprintf("ExportJobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListExportJobsResponseValidationError{
					field:  fmt.Sprintf("ExportJobs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListExportJobsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListExportJobsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListExportJobsResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListExportJobsResponseMultiError(errors)
	}

	return nil
}

// ListExportJobsResponseMultiError is an error wrapping multiple validation
// errors returned by ListExportJobsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListExportJobsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExportJobsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExportJobsResponseMultiError) AllErrors() []error { return m }

// ListExportJobsResponseValidationError is the validation error returned by
// ListExportJobsResponse.Validate if the designated constraints aren't met.
type ListExportJobsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExportJobsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExportJobsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExportJobsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExportJobsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExportJobsResponseValidationError) ErrorName() string {
	return "ListExportJobsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListExportJobsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExportJobsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExportJobsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExportJobsResponseValidationError{}
