// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: llm/v1/key_service.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayKeyService_CreateGatewayKey_FullMethodName = "/llm.v1.GatewayKeyService/CreateGatewayKey"
	GatewayKeyService_GetGatewayKey_FullMethodName    = "/llm.v1.GatewayKeyService/GetGatewayKey"
	GatewayKeyService_ListGatewayKeys_FullMethodName  = "/llm.v1.GatewayKeyService/ListGatewayKeys"
	GatewayKeyService_UpdateGatewayKey_FullMethodName = "/llm.v1.GatewayKeyService/UpdateGatewayKey"
	GatewayKeyService_RotateGatewayKey_FullMethodName = "/llm.v1.GatewayKeyService/RotateGatewayKey"
	GatewayKeyService_RevokeGatewayKey_FullMethodName = "/llm.v1.GatewayKeyService/RevokeGatewayKey"
)

// GatewayKeyServiceClient is the client API for GatewayKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayKeyServiceClient interface {
	CreateGatewayKey(ctx context.Context, in *CreateGatewayKeyRequest, opts ...grpc.CallOption) (*CreateGatewayKeyResponse, error)
	GetGatewayKey(ctx context.Context, in *GetGatewayKeyRequest, opts ...grpc.CallOption) (*GetGatewayKeyResponse, error)
	ListGatewayKeys(ctx context.Context, in *ListGatewayKeysRequest, opts ...grpc.CallOption) (*ListGatewayKeysResponse, error)
	UpdateGatewayKey(ctx context.Context, in *UpdateGatewayKeyRequest, opts ...grpc.CallOption) (*UpdateGatewayKeyResponse, error)
	RotateGatewayKey(ctx context.Context, in *RotateGatewayKeyRequest, opts ...grpc.CallOption) (*RotateGatewayKeyResponse, error)
	RevokeGatewayKey(ctx context.Context, in *RevokeGatewayKeyRequest, opts ...grpc.CallOption) (*RevokeGatewayKeyResponse, error)
}

type gatewayKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayKeyServiceClient(cc grpc.ClientConnInterface) GatewayKeyServiceClient {
	return &gatewayKeyServiceClient{cc}
}

func (c *gatewayKeyServiceClient) CreateGatewayKey(ctx context.Context, in *CreateGatewayKeyRequest, opts ...grpc.CallOption) (*CreateGatewayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGatewayKeyResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_CreateGatewayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayKeyServiceClient) GetGatewayKey(ctx context.Context, in *GetGatewayKeyRequest, opts ...grpc.CallOption) (*GetGatewayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayKeyResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_GetGatewayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayKeyServiceClient) ListGatewayKeys(ctx context.Context, in *ListGatewayKeysRequest, opts ...grpc.CallOption) (*ListGatewayKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewayKeysResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_ListGatewayKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayKeyServiceClient) UpdateGatewayKey(ctx context.Context, in *UpdateGatewayKeyRequest, opts ...grpc.CallOption) (*UpdateGatewayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGatewayKeyResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_UpdateGatewayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayKeyServiceClient) RotateGatewayKey(ctx context.Context, in *RotateGatewayKeyRequest, opts ...grpc.CallOption) (*RotateGatewayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateGatewayKeyResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_RotateGatewayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayKeyServiceClient) RevokeGatewayKey(ctx context.Context, in *RevokeGatewayKeyRequest, opts ...grpc.CallOption) (*RevokeGatewayKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeGatewayKeyResponse)
	err := c.cc.Invoke(ctx, GatewayKeyService_RevokeGatewayKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayKeyServiceServer is the server API for GatewayKeyService service.
// All implementations must embed UnimplementedGatewayKeyServiceServer
// for forward compatibility.
type GatewayKeyServiceServer interface {
	CreateGatewayKey(context.Context, *CreateGatewayKeyRequest) (*CreateGatewayKeyResponse, error)
	GetGatewayKey(context.Context, *GetGatewayKeyRequest) (*GetGatewayKeyResponse, error)
	ListGatewayKeys(context.Context, *ListGatewayKeysRequest) (*ListGatewayKeysResponse, error)
	UpdateGatewayKey(context.Context, *UpdateGatewayKeyRequest) (*UpdateGatewayKeyResponse, error)
	RotateGatewayKey(context.Context, *RotateGatewayKeyRequest) (*RotateGatewayKeyResponse, error)
	RevokeGatewayKey(context.Context, *RevokeGatewayKeyRequest) (*RevokeGatewayKeyResponse, error)
	mustEmbedUnimplementedGatewayKeyServiceServer()
}

// UnimplementedGatewayKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayKeyServiceServer struct{}

func (UnimplementedGatewayKeyServiceServer) CreateGatewayKey(context.Context, *CreateGatewayKeyRequest) (*CreateGatewayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGatewayKey not implemented")
}
func (UnimplementedGatewayKeyServiceServer) GetGatewayKey(context.Context, *GetGatewayKeyRequest) (*GetGatewayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGatewayKey not implemented")
}
func (UnimplementedGatewayKeyServiceServer) ListGatewayKeys(context.Context, *ListGatewayKeysRequest) (*ListGatewayKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGatewayKeys not implemented")
}
func (UnimplementedGatewayKeyServiceServer) UpdateGatewayKey(context.Context, *UpdateGatewayKeyRequest) (*UpdateGatewayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGatewayKey not implemented")
}
func (UnimplementedGatewayKeyServiceServer) RotateGatewayKey(context.Context, *RotateGatewayKeyRequest) (*RotateGatewayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateGatewayKey not implemented")
}
func (UnimplementedGatewayKeyServiceServer) RevokeGatewayKey(context.Context, *RevokeGatewayKeyRequest) (*RevokeGatewayKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeGatewayKey not implemented")
}
func (UnimplementedGatewayKeyServiceServer) mustEmbedUnimplementedGatewayKeyServiceServer() {}
func (UnimplementedGatewayKeyServiceServer) testEmbeddedByValue()                           {}

// UnsafeGatewayKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayKeyServiceServer will
// result in compilation errors.
type UnsafeGatewayKeyServiceServer interface {
	mustEmbedUnimplementedGatewayKeyServiceServer()
}

func RegisterGatewayKeyServiceServer(s grpc.ServiceRegistrar, srv GatewayKeyServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayKeyService_ServiceDesc, srv)
}

func _GatewayKeyService_CreateGatewayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).CreateGatewayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_CreateGatewayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).CreateGatewayKey(ctx, req.(*CreateGatewayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayKeyService_GetGatewayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).GetGatewayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_GetGatewayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).GetGatewayKey(ctx, req.(*GetGatewayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayKeyService_ListGatewayKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).ListGatewayKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_ListGatewayKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).ListGatewayKeys(ctx, req.(*ListGatewayKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayKeyService_UpdateGatewayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).UpdateGatewayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_UpdateGatewayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).UpdateGatewayKey(ctx, req.(*UpdateGatewayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayKeyService_RotateGatewayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateGatewayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).RotateGatewayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_RotateGatewayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).RotateGatewayKey(ctx, req.(*RotateGatewayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayKeyService_RevokeGatewayKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeGatewayKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayKeyServiceServer).RevokeGatewayKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayKeyService_RevokeGatewayKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayKeyServiceServer).RevokeGatewayKey(ctx, req.(*RevokeGatewayKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayKeyService_ServiceDesc is the grpc.ServiceDesc for GatewayKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.GatewayKeyService",
	HandlerType: (*GatewayKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGatewayKey",
			Handler:    _GatewayKeyService_CreateGatewayKey_Handler,
		},
		{
			MethodName: "GetGatewayKey",
			Handler:    _GatewayKeyService_GetGatewayKey_Handler,
		},
		{
			MethodName: "ListGatewayKeys",
			Handler:    _GatewayKeyService_ListGatewayKeys_Handler,
		},
		{
			MethodName: "UpdateGatewayKey",
			Handler:    _GatewayKeyService_UpdateGatewayKey_Handler,
		},
		{
			MethodName: "RotateGatewayKey",
			Handler:    _GatewayKeyService_RotateGatewayKey_Handler,
		},
		{
			MethodName: "RevokeGatewayKey",
			Handler:    _GatewayKeyService_RevokeGatewayKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/key_service.proto",
}

const (
	UpstreamCredentialService_CreateUpstreamCredential_FullMethodName = "/llm.v1.UpstreamCredentialService/CreateUpstreamCredential"
	UpstreamCredentialService_GetUpstreamCredential_FullMethodName    = "/llm.v1.UpstreamCredentialService/GetUpstreamCredential"
	UpstreamCredentialService_ListUpstreamCredentials_FullMethodName  = "/llm.v1.UpstreamCredentialService/ListUpstreamCredentials"
	UpstreamCredentialService_UpdateUpstreamCredential_FullMethodName = "/llm.v1.UpstreamCredentialService/UpdateUpstreamCredential"
	UpstreamCredentialService_RotateUpstreamCredential_FullMethodName = "/llm.v1.UpstreamCredentialService/RotateUpstreamCredential"
)

// UpstreamCredentialServiceClient is the client API for UpstreamCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamCredentialServiceClient interface {
	CreateUpstreamCredential(ctx context.Context, in *CreateUpstreamCredentialRequest, opts ...grpc.CallOption) (*CreateUpstreamCredentialResponse, error)
	GetUpstreamCredential(ctx context.Context, in *GetUpstreamCredentialRequest, opts ...grpc.CallOption) (*GetUpstreamCredentialResponse, error)
	ListUpstreamCredentials(ctx context.Context, in *ListUpstreamCredentialsRequest, opts ...grpc.CallOption) (*ListUpstreamCredentialsResponse, error)
	UpdateUpstreamCredential(ctx context.Context, in *UpdateUpstreamCredentialRequest, opts ...grpc.CallOption) (*UpdateUpstreamCredentialResponse, error)
	RotateUpstreamCredential(ctx context.Context, in *RotateUpstreamCredentialRequest, opts ...grpc.CallOption) (*RotateUpstreamCredentialResponse, error)
}

type upstreamCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamCredentialServiceClient(cc grpc.ClientConnInterface) UpstreamCredentialServiceClient {
	return &upstreamCredentialServiceClient{cc}
}

func (c *upstreamCredentialServiceClient) CreateUpstreamCredential(ctx context.Context, in *CreateUpstreamCredentialRequest, opts ...grpc.CallOption) (*CreateUpstreamCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUpstreamCredentialResponse)
	err := c.cc.Invoke(ctx, UpstreamCredentialService_CreateUpstreamCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamCredentialServiceClient) GetUpstreamCredential(ctx context.Context, in *GetUpstreamCredentialRequest, opts ...grpc.CallOption) (*GetUpstreamCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpstreamCredentialResponse)
	err := c.cc.Invoke(ctx, UpstreamCredentialService_GetUpstreamCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamCredentialServiceClient) ListUpstreamCredentials(ctx context.Context, in *ListUpstreamCredentialsRequest, opts ...grpc.CallOption) (*ListUpstreamCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUpstreamCredentialsResponse)
	err := c.cc.Invoke(ctx, UpstreamCredentialService_ListUpstreamCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamCredentialServiceClient) UpdateUpstreamCredential(ctx context.Context, in *UpdateUpstreamCredentialRequest, opts ...grpc.CallOption) (*UpdateUpstreamCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUpstreamCredentialResponse)
	err := c.cc.Invoke(ctx, UpstreamCredentialService_UpdateUpstreamCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamCredentialServiceClient) RotateUpstreamCredential(ctx context.Context, in *RotateUpstreamCredentialRequest, opts ...grpc.CallOption) (*RotateUpstreamCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateUpstreamCredentialResponse)
	err := c.cc.Invoke(ctx, UpstreamCredentialService_RotateUpstreamCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpstreamCredentialServiceServer is the server API for UpstreamCredentialService service.
// All implementations must embed UnimplementedUpstreamCredentialServiceServer
// for forward compatibility.
type UpstreamCredentialServiceServer interface {
	CreateUpstreamCredential(context.Context, *CreateUpstreamCredentialRequest) (*CreateUpstreamCredentialResponse, error)
	GetUpstreamCredential(context.Context, *GetUpstreamCredentialRequest) (*GetUpstreamCredentialResponse, error)
	ListUpstreamCredentials(context.Context, *ListUpstreamCredentialsRequest) (*ListUpstreamCredentialsResponse, error)
	UpdateUpstreamCredential(context.Context, *UpdateUpstreamCredentialRequest) (*UpdateUpstreamCredentialResponse, error)
	RotateUpstreamCredential(context.Context, *RotateUpstreamCredentialRequest) (*RotateUpstreamCredentialResponse, error)
	mustEmbedUnimplementedUpstreamCredentialServiceServer()
}

// UnimplementedUpstreamCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamCredentialServiceServer struct{}

func (UnimplementedUpstreamCredentialServiceServer) CreateUpstreamCredential(context.Context, *CreateUpstreamCredentialRequest) (*CreateUpstreamCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUpstreamCredential not implemented")
}
func (UnimplementedUpstreamCredentialServiceServer) GetUpstreamCredential(context.Context, *GetUpstreamCredentialRequest) (*GetUpstreamCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpstreamCredential not implemented")
}
func (UnimplementedUpstreamCredentialServiceServer) ListUpstreamCredentials(context.Context, *ListUpstreamCredentialsRequest) (*ListUpstreamCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUpstreamCredentials not implemented")
}
func (UnimplementedUpstreamCredentialServiceServer) UpdateUpstreamCredential(context.Context, *UpdateUpstreamCredentialRequest) (*UpdateUpstreamCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUpstreamCredential not implemented")
}
func (UnimplementedUpstreamCredentialServiceServer) RotateUpstreamCredential(context.Context, *RotateUpstreamCredentialRequest) (*RotateUpstreamCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateUpstreamCredential not implemented")
}
func (UnimplementedUpstreamCredentialServiceServer) mustEmbedUnimplementedUpstreamCredentialServiceServer() {
}
func (UnimplementedUpstreamCredentialServiceServer) testEmbeddedByValue() {}

// UnsafeUpstreamCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamCredentialServiceServer will
// result in compilation errors.
type UnsafeUpstreamCredentialServiceServer interface {
	mustEmbedUnimplementedUpstreamCredentialServiceServer()
}

func RegisterUpstreamCredentialServiceServer(s grpc.ServiceRegistrar, srv UpstreamCredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedUpstreamCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpstreamCredentialService_ServiceDesc, srv)
}

func _UpstreamCredentialService_CreateUpstreamCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpstreamCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamCredentialServiceServer).CreateUpstreamCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamCredentialService_CreateUpstreamCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamCredentialServiceServer).CreateUpstreamCredential(ctx, req.(*CreateUpstreamCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamCredentialService_GetUpstreamCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpstreamCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamCredentialServiceServer).GetUpstreamCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamCredentialService_GetUpstreamCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamCredentialServiceServer).GetUpstreamCredential(ctx, req.(*GetUpstreamCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamCredentialService_ListUpstreamCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpstreamCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamCredentialServiceServer).ListUpstreamCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamCredentialService_ListUpstreamCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamCredentialServiceServer).ListUpstreamCredentials(ctx, req.(*ListUpstreamCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamCredentialService_UpdateUpstreamCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUpstreamCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamCredentialServiceServer).UpdateUpstreamCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamCredentialService_UpdateUpstreamCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamCredentialServiceServer).UpdateUpstreamCredential(ctx, req.(*UpdateUpstreamCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamCredentialService_RotateUpstreamCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateUpstreamCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamCredentialServiceServer).RotateUpstreamCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamCredentialService_RotateUpstreamCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamCredentialServiceServer).RotateUpstreamCredential(ctx, req.(*RotateUpstreamCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpstreamCredentialService_ServiceDesc is the grpc.ServiceDesc for UpstreamCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpstreamCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.UpstreamCredentialService",
	HandlerType: (*UpstreamCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUpstreamCredential",
			Handler:    _UpstreamCredentialService_CreateUpstreamCredential_Handler,
		},
		{
			MethodName: "GetUpstreamCredential",
			Handler:    _UpstreamCredentialService_GetUpstreamCredential_Handler,
		},
		{
			MethodName: "ListUpstreamCredentials",
			Handler:    _UpstreamCredentialService_ListUpstreamCredentials_Handler,
		},
		{
			MethodName: "UpdateUpstreamCredential",
			Handler:    _UpstreamCredentialService_UpdateUpstreamCredential_Handler,
		},
		{
			MethodName: "RotateUpstreamCredential",
			Handler:    _UpstreamCredentialService_RotateUpstreamCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/key_service.proto",
}
