// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: llm/v1/usage_service.proto

package llmv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UsageRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UsageRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsageRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UsageRecordMultiError, or
// nil if none found.
func (m *UsageRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *UsageRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for GatewayKeyId

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	// no validation rules for UpstreamModel

	// no validation rules for RequestId

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	// no validation rules for BillableUnits

	// no validation rules for PricingSnapshotId

	if all {
		switch v := interface{}(m.GetBilledAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "BilledAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "BilledAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBilledAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageRecordValidationError{
				field:  "BilledAmount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageRecordValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageRecordValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageRecordValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageRecordValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UsageRecordMultiError(errors)
	}

	return nil
}

// UsageRecordMultiError is an error wrapping multiple validation errors
// returned by UsageRecord.ValidateAll() if the designated constraints aren't met.
type UsageRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageRecordMultiError) AllErrors() []error { return m }

// UsageRecordValidationError is the validation error returned by
// UsageRecord.Validate if the designated constraints aren't met.
type UsageRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageRecordValidationError) ErrorName() string { return "UsageRecordValidationError" }

// Error satisfies the builtin error interface
func (e UsageRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsageRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageRecordValidationError{}

// Validate checks the field values on UsageSummary with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UsageSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsageSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UsageSummaryMultiError, or
// nil if none found.
func (m *UsageSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *UsageSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageSummaryValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageSummaryValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageSummaryValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for RequestCount

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	// no validation rules for BillableUnits

	if all {
		switch v := interface{}(m.GetBilledAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsageSummaryValidationError{
					field:  "BilledAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsageSummaryValidationError{
					field:  "BilledAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBilledAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsageSummaryValidationError{
				field:  "BilledAmount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UsageSummaryMultiError(errors)
	}

	return nil
}

// UsageSummaryMultiError is an error wrapping multiple validation errors
// returned by UsageSummary.ValidateAll() if the designated constraints aren't met.
type UsageSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageSummaryMultiError) AllErrors() []error { return m }

// UsageSummaryValidationError is the validation error returned by
// UsageSummary.Validate if the designated constraints aren't met.
type UsageSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageSummaryValidationError) ErrorName() string { return "UsageSummaryValidationError" }

// Error satisfies the builtin error interface
func (e UsageSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsageSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageSummaryValidationError{}

// Validate checks the field values on PricingDimension with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PricingDimension) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PricingDimension with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PricingDimensionMultiError, or nil if none found.
func (m *PricingDimension) ValidateAll() error {
	return m.validate(true)
}

func (m *PricingDimension) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Unit

	if all {
		switch v := interface{}(m.GetPrice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PricingDimensionValidationError{
					field:  "Price",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PricingDimensionValidationError{
					field:  "Price",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PricingDimensionValidationError{
				field:  "Price",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PricingDimensionMultiError(errors)
	}

	return nil
}

// PricingDimensionMultiError is an error wrapping multiple validation errors
// returned by PricingDimension.ValidateAll() if the designated constraints
// aren't met.
type PricingDimensionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PricingDimensionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PricingDimensionMultiError) AllErrors() []error { return m }

// PricingDimensionValidationError is the validation error returned by
// PricingDimension.Validate if the designated constraints aren't met.
type PricingDimensionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PricingDimensionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PricingDimensionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PricingDimensionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PricingDimensionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PricingDimensionValidationError) ErrorName() string { return "PricingDimensionValidationError" }

// Error satisfies the builtin error interface
func (e PricingDimensionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPricingDimension.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PricingDimensionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PricingDimensionValidationError{}

// Validate checks the field values on PricingSnapshot with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PricingSnapshot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PricingSnapshot with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PricingSnapshotMultiError, or nil if none found.
func (m *PricingSnapshot) ValidateAll() error {
	return m.validate(true)
}

func (m *PricingSnapshot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	// no validation rules for DisplayName

	for idx, item := range m.GetDimensions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PricingSnapshotValidationError{
						field:  fmt.Sprintf("Dimensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PricingSnapshotValidationError{
						field:  fmt.Sprintf("Dimensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PricingSnapshotValidationError{
					field:  fmt.Sprintf("Dimensions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetEffectiveAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "EffectiveAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "EffectiveAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEffectiveAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PricingSnapshotValidationError{
				field:  "EffectiveAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PricingSnapshotValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PricingSnapshotValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PricingSnapshotValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PricingSnapshotMultiError(errors)
	}

	return nil
}

// PricingSnapshotMultiError is an error wrapping multiple validation errors
// returned by PricingSnapshot.ValidateAll() if the designated constraints
// aren't met.
type PricingSnapshotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PricingSnapshotMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PricingSnapshotMultiError) AllErrors() []error { return m }

// PricingSnapshotValidationError is the validation error returned by
// PricingSnapshot.Validate if the designated constraints aren't met.
type PricingSnapshotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PricingSnapshotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PricingSnapshotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PricingSnapshotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PricingSnapshotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PricingSnapshotValidationError) ErrorName() string { return "PricingSnapshotValidationError" }

// Error satisfies the builtin error interface
func (e PricingSnapshotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPricingSnapshot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PricingSnapshotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PricingSnapshotValidationError{}

// Validate checks the field values on Balance with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Balance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Balance with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BalanceMultiError, or nil if none found.
func (m *Balance) ValidateAll() error {
	return m.validate(true)
}

func (m *Balance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for BillingMode

	if all {
		switch v := interface{}(m.GetAvailableBalance()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "AvailableBalance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "AvailableBalance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAvailableBalance()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BalanceValidationError{
				field:  "AvailableBalance",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCurrentPeriodSpend()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "CurrentPeriodSpend",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "CurrentPeriodSpend",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCurrentPeriodSpend()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BalanceValidationError{
				field:  "CurrentPeriodSpend",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOutstandingAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "OutstandingAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "OutstandingAmount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOutstandingAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BalanceValidationError{
				field:  "OutstandingAmount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAsOfTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "AsOfTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BalanceValidationError{
					field:  "AsOfTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAsOfTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BalanceValidationError{
				field:  "AsOfTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BalanceMultiError(errors)
	}

	return nil
}

// BalanceMultiError is an error wrapping multiple validation errors returned
// by Balance.ValidateAll() if the designated constraints aren't met.
type BalanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BalanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BalanceMultiError) AllErrors() []error { return m }

// BalanceValidationError is the validation error returned by Balance.Validate
// if the designated constraints aren't met.
type BalanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BalanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BalanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BalanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BalanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BalanceValidationError) ErrorName() string { return "BalanceValidationError" }

// Error satisfies the builtin error interface
func (e BalanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBalance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BalanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BalanceValidationError{}

// Validate checks the field values on InvoiceLineItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InvoiceLineItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InvoiceLineItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InvoiceLineItemMultiError, or nil if none found.
func (m *InvoiceLineItem) ValidateAll() error {
	return m.validate(true)
}

func (m *InvoiceLineItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UsageRecordId

	// no validation rules for Description

	// no validation rules for Quantity

	if all {
		switch v := interface{}(m.GetUnitPrice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceLineItemValidationError{
					field:  "UnitPrice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceLineItemValidationError{
					field:  "UnitPrice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUnitPrice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceLineItemValidationError{
				field:  "UnitPrice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceLineItemValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceLineItemValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceLineItemValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InvoiceLineItemMultiError(errors)
	}

	return nil
}

// InvoiceLineItemMultiError is an error wrapping multiple validation errors
// returned by InvoiceLineItem.ValidateAll() if the designated constraints
// aren't met.
type InvoiceLineItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InvoiceLineItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InvoiceLineItemMultiError) AllErrors() []error { return m }

// InvoiceLineItemValidationError is the validation error returned by
// InvoiceLineItem.Validate if the designated constraints aren't met.
type InvoiceLineItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InvoiceLineItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InvoiceLineItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InvoiceLineItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InvoiceLineItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InvoiceLineItemValidationError) ErrorName() string { return "InvoiceLineItemValidationError" }

// Error satisfies the builtin error interface
func (e InvoiceLineItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInvoiceLineItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InvoiceLineItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InvoiceLineItemValidationError{}

// Validate checks the field values on Invoice with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Invoice) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Invoice with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in InvoiceMultiError, or nil if none found.
func (m *Invoice) ValidateAll() error {
	return m.validate(true)
}

func (m *Invoice) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for BillingPeriod

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetSubtotal()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Subtotal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Subtotal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubtotal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "Subtotal",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTax()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Tax",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Tax",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTax()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "Tax",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTotal()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Total",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Total",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTotal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "Total",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDueAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "DueAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "DueAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDueAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "DueAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPaidAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "PaidAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "PaidAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPaidAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "PaidAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetLineItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InvoiceValidationError{
						field:  fmt.Sprintf("LineItems[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InvoiceValidationError{
						field:  fmt.Sprintf("LineItems[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InvoiceValidationError{
					field:  fmt.Sprintf("LineItems[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InvoiceValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InvoiceValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InvoiceMultiError(errors)
	}

	return nil
}

// InvoiceMultiError is an error wrapping multiple validation errors returned
// by Invoice.ValidateAll() if the designated constraints aren't met.
type InvoiceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InvoiceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InvoiceMultiError) AllErrors() []error { return m }

// InvoiceValidationError is the validation error returned by Invoice.Validate
// if the designated constraints aren't met.
type InvoiceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InvoiceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InvoiceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InvoiceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InvoiceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InvoiceValidationError) ErrorName() string { return "InvoiceValidationError" }

// Error satisfies the builtin error interface
func (e InvoiceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInvoice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InvoiceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InvoiceValidationError{}

// Validate checks the field values on ListUsageRecordsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUsageRecordsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsageRecordsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUsageRecordsRequestMultiError, or nil if none found.
func (m *ListUsageRecordsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsageRecordsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for GatewayKeyId

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUsageRecordsRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUsageRecordsRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUsageRecordsRequestValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUsageRecordsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUsageRecordsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUsageRecordsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListUsageRecordsRequestMultiError(errors)
	}

	return nil
}

// ListUsageRecordsRequestMultiError is an error wrapping multiple validation
// errors returned by ListUsageRecordsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListUsageRecordsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsageRecordsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsageRecordsRequestMultiError) AllErrors() []error { return m }

// ListUsageRecordsRequestValidationError is the validation error returned by
// ListUsageRecordsRequest.Validate if the designated constraints aren't met.
type ListUsageRecordsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsageRecordsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsageRecordsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsageRecordsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsageRecordsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsageRecordsRequestValidationError) ErrorName() string {
	return "ListUsageRecordsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListUsageRecordsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsageRecordsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsageRecordsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsageRecordsRequestValidationError{}

// Validate checks the field values on ListUsageRecordsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUsageRecordsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsageRecordsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUsageRecordsResponseMultiError, or nil if none found.
func (m *ListUsageRecordsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsageRecordsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUsageRecords() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListUsageRecordsResponseValidationError{
						field:  fmt.Sprintf("UsageRecords[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListUsageRecordsResponseValidationError{
						field:  fmt.Sprintf("UsageRecords[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListUsageRecordsResponseValidationError{
					field:  fmt.Sprintf("UsageRecords[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUsageRecordsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUsageRecordsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUsageRecordsResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListUsageRecordsResponseMultiError(errors)
	}

	return nil
}

// ListUsageRecordsResponseMultiError is an error wrapping multiple validation
// errors returned by ListUsageRecordsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListUsageRecordsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsageRecordsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsageRecordsResponseMultiError) AllErrors() []error { return m }

// ListUsageRecordsResponseValidationError is the validation error returned by
// ListUsageRecordsResponse.Validate if the designated constraints aren't met.
type ListUsageRecordsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsageRecordsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsageRecordsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsageRecordsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsageRecordsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsageRecordsResponseValidationError) ErrorName() string {
	return "ListUsageRecordsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListUsageRecordsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsageRecordsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsageRecordsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsageRecordsResponseValidationError{}

// Validate checks the field values on GetUsageSummaryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUsageSummaryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUsageSummaryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUsageSummaryRequestMultiError, or nil if none found.
func (m *GetUsageSummaryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUsageSummaryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUsageSummaryRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUsageSummaryRequestValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUsageSummaryRequestValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUsageSummaryRequestMultiError(errors)
	}

	return nil
}

// GetUsageSummaryRequestMultiError is an error wrapping multiple validation
// errors returned by GetUsageSummaryRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUsageSummaryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUsageSummaryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUsageSummaryRequestMultiError) AllErrors() []error { return m }

// GetUsageSummaryRequestValidationError is the validation error returned by
// GetUsageSummaryRequest.Validate if the designated constraints aren't met.
type GetUsageSummaryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUsageSummaryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUsageSummaryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUsageSummaryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUsageSummaryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUsageSummaryRequestValidationError) ErrorName() string {
	return "GetUsageSummaryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUsageSummaryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUsageSummaryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUsageSummaryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUsageSummaryRequestValidationError{}

// Validate checks the field values on GetUsageSummaryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUsageSummaryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUsageSummaryResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUsageSummaryResponseMultiError, or nil if none found.
func (m *GetUsageSummaryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUsageSummaryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSummaries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUsageSummaryResponseValidationError{
						field:  fmt.Sprintf("Summaries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUsageSummaryResponseValidationError{
						field:  fmt.Sprintf("Summaries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUsageSummaryResponseValidationError{
					field:  fmt.Sprintf("Summaries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUsageSummaryResponseMultiError(errors)
	}

	return nil
}

// GetUsageSummaryResponseMultiError is an error wrapping multiple validation
// errors returned by GetUsageSummaryResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUsageSummaryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUsageSummaryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUsageSummaryResponseMultiError) AllErrors() []error { return m }

// GetUsageSummaryResponseValidationError is the validation error returned by
// GetUsageSummaryResponse.Validate if the designated constraints aren't met.
type GetUsageSummaryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUsageSummaryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUsageSummaryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUsageSummaryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUsageSummaryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUsageSummaryResponseValidationError) ErrorName() string {
	return "GetUsageSummaryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUsageSummaryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUsageSummaryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUsageSummaryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUsageSummaryResponseValidationError{}

// Validate checks the field values on ListPricingSnapshotsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPricingSnapshotsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPricingSnapshotsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPricingSnapshotsRequestMultiError, or nil if none found.
func (m *ListPricingSnapshotsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPricingSnapshotsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LogicalModelId

	// no validation rules for VendorId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPricingSnapshotsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPricingSnapshotsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPricingSnapshotsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListPricingSnapshotsRequestMultiError(errors)
	}

	return nil
}

// ListPricingSnapshotsRequestMultiError is an error wrapping multiple
// validation errors returned by ListPricingSnapshotsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListPricingSnapshotsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPricingSnapshotsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPricingSnapshotsRequestMultiError) AllErrors() []error { return m }

// ListPricingSnapshotsRequestValidationError is the validation error returned
// by ListPricingSnapshotsRequest.Validate if the designated constraints
// aren't met.
type ListPricingSnapshotsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPricingSnapshotsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPricingSnapshotsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPricingSnapshotsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPricingSnapshotsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPricingSnapshotsRequestValidationError) ErrorName() string {
	return "ListPricingSnapshotsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPricingSnapshotsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPricingSnapshotsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPricingSnapshotsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPricingSnapshotsRequestValidationError{}

// Validate checks the field values on ListPricingSnapshotsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPricingSnapshotsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPricingSnapshotsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPricingSnapshotsResponseMultiError, or nil if none found.
func (m *ListPricingSnapshotsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPricingSnapshotsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPricingSnapshots() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPricingSnapshotsResponseValidationError{
						field:  fmt.Sprintf("PricingSnapshots[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPricingSnapshotsResponseValidationError{
						field:  fmt.Sprintf("PricingSnapshots[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPricingSnapshotsResponseValidationError{
					field:  fmt.Sprintf("PricingSnapshots[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPricingSnapshotsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPricingSnapshotsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPricingSnapshotsResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListPricingSnapshotsResponseMultiError(errors)
	}

	return nil
}

// ListPricingSnapshotsResponseMultiError is an error wrapping multiple
// validation errors returned by ListPricingSnapshotsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListPricingSnapshotsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPricingSnapshotsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPricingSnapshotsResponseMultiError) AllErrors() []error { return m }

// ListPricingSnapshotsResponseValidationError is the validation error returned
// by ListPricingSnapshotsResponse.Validate if the designated constraints
// aren't met.
type ListPricingSnapshotsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPricingSnapshotsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPricingSnapshotsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPricingSnapshotsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPricingSnapshotsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPricingSnapshotsResponseValidationError) ErrorName() string {
	return "ListPricingSnapshotsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPricingSnapshotsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPricingSnapshotsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPricingSnapshotsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPricingSnapshotsResponseValidationError{}

// Validate checks the field values on GetBalanceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBalanceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBalanceRequestMultiError, or nil if none found.
func (m *GetBalanceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBalanceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return GetBalanceRequestMultiError(errors)
	}

	return nil
}

// GetBalanceRequestMultiError is an error wrapping multiple validation errors
// returned by GetBalanceRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBalanceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBalanceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBalanceRequestMultiError) AllErrors() []error { return m }

// GetBalanceRequestValidationError is the validation error returned by
// GetBalanceRequest.Validate if the designated constraints aren't met.
type GetBalanceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBalanceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBalanceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBalanceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBalanceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBalanceRequestValidationError) ErrorName() string {
	return "GetBalanceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBalanceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBalanceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBalanceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBalanceRequestValidationError{}

// Validate checks the field values on GetBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBalanceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBalanceResponseMultiError, or nil if none found.
func (m *GetBalanceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBalanceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBalance()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBalanceResponseValidationError{
					field:  "Balance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBalanceResponseValidationError{
					field:  "Balance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBalance()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBalanceResponseValidationError{
				field:  "Balance",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBalanceResponseMultiError(errors)
	}

	return nil
}

// GetBalanceResponseMultiError is an error wrapping multiple validation errors
// returned by GetBalanceResponse.ValidateAll() if the designated constraints
// aren't met.
type GetBalanceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBalanceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBalanceResponseMultiError) AllErrors() []error { return m }

// GetBalanceResponseValidationError is the validation error returned by
// GetBalanceResponse.Validate if the designated constraints aren't met.
type GetBalanceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBalanceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBalanceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBalanceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBalanceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBalanceResponseValidationError) ErrorName() string {
	return "GetBalanceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBalanceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBalanceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBalanceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBalanceResponseValidationError{}

// Validate checks the field values on ListInvoicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListInvoicesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListInvoicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListInvoicesRequestMultiError, or nil if none found.
func (m *ListInvoicesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListInvoicesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListInvoicesRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListInvoicesRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListInvoicesRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListInvoicesRequestMultiError(errors)
	}

	return nil
}

// ListInvoicesRequestMultiError is an error wrapping multiple validation
// errors returned by ListInvoicesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListInvoicesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListInvoicesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListInvoicesRequestMultiError) AllErrors() []error { return m }

// ListInvoicesRequestValidationError is the validation error returned by
// ListInvoicesRequest.Validate if the designated constraints aren't met.
type ListInvoicesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListInvoicesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListInvoicesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListInvoicesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListInvoicesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListInvoicesRequestValidationError) ErrorName() string {
	return "ListInvoicesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListInvoicesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListInvoicesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListInvoicesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListInvoicesRequestValidationError{}

// Validate checks the field values on ListInvoicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListInvoicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListInvoicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListInvoicesResponseMultiError, or nil if none found.
func (m *ListInvoicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListInvoicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetInvoices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListInvoicesResponseValidationError{
						field:  fmt.Sprintf("Invoices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListInvoicesResponseValidationError{
						field:  fmt.Sprintf("Invoices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListInvoicesResponseValidationError{
					field:  fmt.Sprintf("Invoices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListInvoicesResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListInvoicesResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListInvoicesResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListInvoicesResponseMultiError(errors)
	}

	return nil
}

// ListInvoicesResponseMultiError is an error wrapping multiple validation
// errors returned by ListInvoicesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListInvoicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListInvoicesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListInvoicesResponseMultiError) AllErrors() []error { return m }

// ListInvoicesResponseValidationError is the validation error returned by
// ListInvoicesResponse.Validate if the designated constraints aren't met.
type ListInvoicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListInvoicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListInvoicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListInvoicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListInvoicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListInvoicesResponseValidationError) ErrorName() string {
	return "ListInvoicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListInvoicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListInvoicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListInvoicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListInvoicesResponseValidationError{}

// Validate checks the field values on GetInvoiceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetInvoiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetInvoiceRequestMultiError, or nil if none found.
func (m *GetInvoiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetInvoiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InvoiceId

	if len(errors) > 0 {
		return GetInvoiceRequestMultiError(errors)
	}

	return nil
}

// GetInvoiceRequestMultiError is an error wrapping multiple validation errors
// returned by GetInvoiceRequest.ValidateAll() if the designated constraints
// aren't met.
type GetInvoiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetInvoiceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetInvoiceRequestMultiError) AllErrors() []error { return m }

// GetInvoiceRequestValidationError is the validation error returned by
// GetInvoiceRequest.Validate if the designated constraints aren't met.
type GetInvoiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetInvoiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetInvoiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetInvoiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetInvoiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetInvoiceRequestValidationError) ErrorName() string {
	return "GetInvoiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetInvoiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetInvoiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetInvoiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetInvoiceRequestValidationError{}

// Validate checks the field values on GetInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetInvoiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetInvoiceResponseMultiError, or nil if none found.
func (m *GetInvoiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetInvoiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInvoice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInvoice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetInvoiceResponseValidationError{
				field:  "Invoice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetInvoiceResponseMultiError(errors)
	}

	return nil
}

// GetInvoiceResponseMultiError is an error wrapping multiple validation errors
// returned by GetInvoiceResponse.ValidateAll() if the designated constraints
// aren't met.
type GetInvoiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetInvoiceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetInvoiceResponseMultiError) AllErrors() []error { return m }

// GetInvoiceResponseValidationError is the validation error returned by
// GetInvoiceResponse.Validate if the designated constraints aren't met.
type GetInvoiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetInvoiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetInvoiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetInvoiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetInvoiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetInvoiceResponseValidationError) ErrorName() string {
	return "GetInvoiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetInvoiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetInvoiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetInvoiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetInvoiceResponseValidationError{}
